//          Copyright Jean Pierre Cimalando 2018.
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE or copy at
//          http://www.boost.org/LICENSE_1_0.txt)

#include "insnames.h"
#include <unordered_map>

const char *midi_instrument_name[128] = {
    "Acoustic Grand Piano",
    "Bright Acoustic Piano",
    "Electric Grand Piano",
    "Honky-Tonk Piano",
    "Rhodes Piano",
    "Chorused Piano",
    "Harpsichord",
    "Clavinet",
    "Celesta",
    "Glockenspiel",
    "Music box",
    "Vibraphone",
    "Marimba",
    "Xylophone",
    "Tubular Bells",
    "Dulcimer",
    "Hammond Organ",
    "Percussive Organ",
    "Rock Organ",
    "Church Organ",
    "Reed Organ",
    "Accordion",
    "Harmonica",
    "Tango Accordion",
    "Acoustic Guitar (nylon)",
    "Acoustic Guitar (steel)",
    "Electric Guitar (jazz)",
    "Electric Guitar (clean)",
    "Electric Guitar (muted)",
    "Overdrive Guitar",
    "Distorton Guitar",
    "Guitar Harmonics",
    "Acoustic Bass",
    "Electric Bass (finger)",
    "Electric Bass (pick)",
    "Fretless Bass",
    "Slap Bass 1",
    "Slap Bass 2",
    "Synth Bass 1",
    "Synth Bass 2",
    "Violin",
    "Viola",
    "Cello",
    "Contrabass",
    "Tremolo Strings",
    "Pizzicato String",
    "Orchestral Harp",
    "Timpany",
    "String Ensemble 1",
    "String Ensemble 2",
    "Synth Strings 1",
    "Synth Strings 2",
    "Choir Aahs",
    "Voice Oohs",
    "Synth Voice",
    "Orchestra Hit",
    "Trumpet",
    "Trombone",
    "Tuba",
    "Muted Trumpet",
    "French Horn",
    "Brass Section",
    "Synth Brass 1",
    "Synth Brass 2",
    "Soprano Sax",
    "Alto Sax",
    "Tenor Sax",
    "Baritone Sax",
    "Oboe",
    "English Horn",
    "Bassoon",
    "Clarinet",
    "Piccolo",
    "Flute",
    "Recorder",
    "Pan Flute",
    "Bottle Blow",
    "Shakuhachi",
    "Whistle",
    "Ocarina",
    "Lead 1 (Square)",
    "Lead 2 (Sawtooth)",
    "Lead 3 (Calliope)",
    "Lead 4 (Chiff)",
    "Lead 5 (Charang)",
    "Lead 6 (Voice)",
    "Lead 7 (Fifths)",
    "Lead 8 (Lead+Bass)",
    "Pad 1 (New age)",
    "Pad 2 (Warm)",
    "Pad 3 (Polysynth)",
    "Pad 4 (Choir)",
    "Pad 5 (Bowed)",
    "Pad 6 (Metallic)",
    "Pad 7 (Halo)",
    "Pad 8 (Sweep)",
    "FX 1 (Rain)",
    "FX 2 (Soundtrack)",
    "FX 3 (Crystal)",
    "FX 4 (Atmosphere)",
    "FX 5 (Brightness)",
    "FX 6 (Goblins)",
    "FX 7 (Echoes)",
    "FX 8 (Sci-fi)",
    "Sitar",
    "Banjo",
    "Shamisen",
    "Koto",
    "Kalimba",
    "Bagpipe",
    "Fiddle",
    "Shanai",
    "Tinkle Bell",
    "Agogo Bells",
    "Steel Drums",
    "Woodblock",
    "Taiko Drum",
    "Melodic Tom",
    "Synth Drum",
    "Reverse Cymbal",
    "Guitar Fret Noise",
    "Breath Noise",
    "Seashore",
    "Bird Tweet",
    "Telephone",
    "Helicopter",
    "Applause/Noise",
    "Gunshot"
};

const Midi_Program_Ex midi_percussion[128] = {
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 0>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 1>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 2>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 3>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 4>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 5>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 6>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 7>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 8>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 9>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 10>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 11>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 12>"},
    Midi_Program_Ex{Midi_Spec::XG, "Surdo Mute"},
    Midi_Program_Ex{Midi_Spec::XG, "Surdo Open"},
    Midi_Program_Ex{Midi_Spec::XG, "High Q"},
    Midi_Program_Ex{Midi_Spec::XG, "Whip Slap"},
    Midi_Program_Ex{Midi_Spec::XG, "Scratch Push"},
    Midi_Program_Ex{Midi_Spec::XG, "Scratch Pull"},
    Midi_Program_Ex{Midi_Spec::XG, "Finger Snap"},
    Midi_Program_Ex{Midi_Spec::XG, "Click Noise"},
    Midi_Program_Ex{Midi_Spec::XG, "Metronome Click"},
    Midi_Program_Ex{Midi_Spec::XG, "Metronome Bell"},
    Midi_Program_Ex{Midi_Spec::XG, "Seq Click L"},
    Midi_Program_Ex{Midi_Spec::XG, "Seq Click H"},
    Midi_Program_Ex{Midi_Spec::XG, "Brush Tap"},
    Midi_Program_Ex{Midi_Spec::XG, "Brush Swirl L"},
    Midi_Program_Ex{Midi_Spec::GS, "High Q"},  // (XG) Brush Slap
    Midi_Program_Ex{Midi_Spec::GS, "Slap"},  // (XG) Brush Swirl H
    Midi_Program_Ex{Midi_Spec::GS, "Scratch Push"},  // (XG) Snare Roll
    Midi_Program_Ex{Midi_Spec::GS, "Scratch Pull"},  // (XG) Castanet
    Midi_Program_Ex{Midi_Spec::GS, "Sticks"},  // (XG) Snare L
    Midi_Program_Ex{Midi_Spec::GS, "Square Click"},  // (XG) Sticks
    Midi_Program_Ex{Midi_Spec::GS, "Metronome Click"},  // (XG) Bass Drum L
    Midi_Program_Ex{Midi_Spec::GS, "Metronome Bell"},  // (XG) Open Rim Shot
    Midi_Program_Ex{Midi_Spec::GM, "Acoustic Bass Drum"},
    Midi_Program_Ex{Midi_Spec::GM, "Bass Drum 1"},
    Midi_Program_Ex{Midi_Spec::GM, "Side Stick"},
    Midi_Program_Ex{Midi_Spec::GM, "Acoustic Snare"},
    Midi_Program_Ex{Midi_Spec::GM, "Hand Clap"},
    Midi_Program_Ex{Midi_Spec::GM, "Electric Snare"},
    Midi_Program_Ex{Midi_Spec::GM, "Low Floor Tom"},
    Midi_Program_Ex{Midi_Spec::GM, "Closed High Hat"},
    Midi_Program_Ex{Midi_Spec::GM, "High Floor Tom"},
    Midi_Program_Ex{Midi_Spec::GM, "Pedal High Hat"},
    Midi_Program_Ex{Midi_Spec::GM, "Low Tom"},
    Midi_Program_Ex{Midi_Spec::GM, "Open High Hat"},
    Midi_Program_Ex{Midi_Spec::GM, "Low-Mid Tom"},
    Midi_Program_Ex{Midi_Spec::GM, "High-Mid Tom"},
    Midi_Program_Ex{Midi_Spec::GM, "Crash Cymbal 1"},
    Midi_Program_Ex{Midi_Spec::GM, "High Tom"},
    Midi_Program_Ex{Midi_Spec::GM, "Ride Cymbal 1"},
    Midi_Program_Ex{Midi_Spec::GM, "Chinese Cymbal"},
    Midi_Program_Ex{Midi_Spec::GM, "Ride Bell"},
    Midi_Program_Ex{Midi_Spec::GM, "Tambourine"},
    Midi_Program_Ex{Midi_Spec::GM, "Splash Cymbal"},
    Midi_Program_Ex{Midi_Spec::GM, "Cow Bell"},
    Midi_Program_Ex{Midi_Spec::GM, "Crash Cymbal 2"},
    Midi_Program_Ex{Midi_Spec::GM, "Vibraslap"},
    Midi_Program_Ex{Midi_Spec::GM, "Ride Cymbal 2"},
    Midi_Program_Ex{Midi_Spec::GM, "High Bongo"},
    Midi_Program_Ex{Midi_Spec::GM, "Low Bongo"},
    Midi_Program_Ex{Midi_Spec::GM, "Mute High Conga"},
    Midi_Program_Ex{Midi_Spec::GM, "Open High Conga"},
    Midi_Program_Ex{Midi_Spec::GM, "Low Conga"},
    Midi_Program_Ex{Midi_Spec::GM, "High Timbale"},
    Midi_Program_Ex{Midi_Spec::GM, "Low Timbale"},
    Midi_Program_Ex{Midi_Spec::GM, "High Agogo"},
    Midi_Program_Ex{Midi_Spec::GM, "Low Agogo"},
    Midi_Program_Ex{Midi_Spec::GM, "Cabasa"},
    Midi_Program_Ex{Midi_Spec::GM, "Maracas"},
    Midi_Program_Ex{Midi_Spec::GM, "Short Whistle"},
    Midi_Program_Ex{Midi_Spec::GM, "Long Whistle"},
    Midi_Program_Ex{Midi_Spec::GM, "Short Guiro"},
    Midi_Program_Ex{Midi_Spec::GM, "Long Guiro"},
    Midi_Program_Ex{Midi_Spec::GM, "Claves"},
    Midi_Program_Ex{Midi_Spec::GM, "High Wood Block"},
    Midi_Program_Ex{Midi_Spec::GM, "Low Wood Block"},
    Midi_Program_Ex{Midi_Spec::GM, "Mute Cuica"},
    Midi_Program_Ex{Midi_Spec::GM, "Open Cuica"},
    Midi_Program_Ex{Midi_Spec::GM, "Mute Triangle"},
    Midi_Program_Ex{Midi_Spec::GM, "Open Triangle"},
    Midi_Program_Ex{Midi_Spec::GS, "Shaker"},
    Midi_Program_Ex{Midi_Spec::GS, "Jingle Bell"},
    Midi_Program_Ex{Midi_Spec::GS, "Bell Tree"},
    Midi_Program_Ex{Midi_Spec::GS, "Castanets"},
    Midi_Program_Ex{Midi_Spec::GS, "Mute Surdu"},
    Midi_Program_Ex{Midi_Spec::GS, "Open Surdu"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 88>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 89>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 90>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 91>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 92>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 93>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 94>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 95>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 96>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 97>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 98>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 99>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 100>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 101>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 102>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 103>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 104>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 105>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 106>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 107>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 108>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 109>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 110>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 111>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 112>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 113>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 114>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 115>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 116>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 117>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 118>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 119>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 120>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 121>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 122>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 123>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 124>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 125>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 126>"},
    Midi_Program_Ex{Midi_Spec::GM, "<Reserved 127>"},
};

const char *midi_spec_name(Midi_Spec spec)
{
    switch (spec) {
    case Midi_Spec::GM: return "GM";
    case Midi_Spec::GS: return "GS";
    case Midi_Spec::SC88: return "SC88";
    case Midi_Spec::MT32: return "MT32";
    case Midi_Spec::XG: return "XG";
    }
    return nullptr;
}

inline unsigned midi_program_ex_id(
    unsigned msb, unsigned lsb, unsigned pgm)
{
    return ((msb & 0x7f) << 14) | ((lsb & 0x7f) << 7) | (pgm & 0x7f);
}

static const std::unordered_map<unsigned, Midi_Program_Ex> midi_program_ex_map = {
    {midi_program_ex_id(0x1, 00, 0x26), Midi_Program_Ex{Midi_Spec::GS, "Synth Bass 101"}},
    {midi_program_ex_id(0x1, 00, 0x39), Midi_Program_Ex{Midi_Spec::GS, "Trombone 2"}},
    {midi_program_ex_id(0x1, 00, 0x3c), Midi_Program_Ex{Midi_Spec::GS, "French Horn2"}},
    {midi_program_ex_id(0x1, 00, 0x50), Midi_Program_Ex{Midi_Spec::GS, "Square"}},
    {midi_program_ex_id(0x1, 00, 0x51), Midi_Program_Ex{Midi_Spec::GS, "Saw"}},
    {midi_program_ex_id(0x1, 00, 0x62), Midi_Program_Ex{Midi_Spec::GS, "Syn Mallet"}},
    {midi_program_ex_id(0x1, 00, 0x66), Midi_Program_Ex{Midi_Spec::GS, "Echo Bell"}},
    {midi_program_ex_id(0x1, 00, 0x68), Midi_Program_Ex{Midi_Spec::GS, "Sitar 2"}},
    {midi_program_ex_id(0x1, 00, 0x78), Midi_Program_Ex{Midi_Spec::GS, "Gt. Cut Noise"}},
    {midi_program_ex_id(0x1, 00, 0x79), Midi_Program_Ex{Midi_Spec::GS, "Flute Key Click"}},
    {midi_program_ex_id(0x1, 00, 0x7a), Midi_Program_Ex{Midi_Spec::GS, "Rain"}},
    {midi_program_ex_id(0x1, 00, 0x7b), Midi_Program_Ex{Midi_Spec::GS, "Dog"}},
    {midi_program_ex_id(0x1, 00, 0x7c), Midi_Program_Ex{Midi_Spec::GS, "Telephone 2"}},
    {midi_program_ex_id(0x1, 00, 0x7d), Midi_Program_Ex{Midi_Spec::GS, "Car-Engine"}},
    {midi_program_ex_id(0x1, 00, 0x7e), Midi_Program_Ex{Midi_Spec::GS, "Laughing"}},
    {midi_program_ex_id(0x1, 00, 0x7f), Midi_Program_Ex{Midi_Spec::GS, "Machine Gun"}},
    {midi_program_ex_id(0x2, 00, 0x66), Midi_Program_Ex{Midi_Spec::GS, "Echo Pan"}},
    {midi_program_ex_id(0x2, 00, 0x78), Midi_Program_Ex{Midi_Spec::GS, "String Slap"}},
    {midi_program_ex_id(0x2, 00, 0x7a), Midi_Program_Ex{Midi_Spec::GS, "Thunder"}},
    {midi_program_ex_id(0x2, 00, 0x7b), Midi_Program_Ex{Midi_Spec::GS, "Horse-Gallop"}},
    {midi_program_ex_id(0x2, 00, 0x7c), Midi_Program_Ex{Midi_Spec::GS, "Door Creaking"}},
    {midi_program_ex_id(0x2, 00, 0x7d), Midi_Program_Ex{Midi_Spec::GS, "Car-Stop"}},
    {midi_program_ex_id(0x2, 00, 0x7e), Midi_Program_Ex{Midi_Spec::GS, "Screaming"}},
    {midi_program_ex_id(0x2, 00, 0x7f), Midi_Program_Ex{Midi_Spec::GS, "Lasergun"}},
    {midi_program_ex_id(0x3, 00, 0x7a), Midi_Program_Ex{Midi_Spec::GS, "Wind"}},
    {midi_program_ex_id(0x3, 00, 0x7b), Midi_Program_Ex{Midi_Spec::GS, "Bird 2"}},
    {midi_program_ex_id(0x3, 00, 0x7c), Midi_Program_Ex{Midi_Spec::GS, "Door Close"}},
    {midi_program_ex_id(0x3, 00, 0x7d), Midi_Program_Ex{Midi_Spec::GS, "Car-Pass"}},
    {midi_program_ex_id(0x3, 00, 0x7e), Midi_Program_Ex{Midi_Spec::GS, "Punch"}},
    {midi_program_ex_id(0x3, 00, 0x7f), Midi_Program_Ex{Midi_Spec::GS, "Explosion"}},
    {midi_program_ex_id(0x4, 00, 0x7a), Midi_Program_Ex{Midi_Spec::GS, "Stream"}},
    {midi_program_ex_id(0x4, 00, 0x7c), Midi_Program_Ex{Midi_Spec::GS, "Scratch"}},
    {midi_program_ex_id(0x4, 00, 0x7d), Midi_Program_Ex{Midi_Spec::GS, "Car-Crash"}},
    {midi_program_ex_id(0x4, 00, 0x7e), Midi_Program_Ex{Midi_Spec::GS, "Heart Beat"}},
    {midi_program_ex_id(0x5, 00, 0x7a), Midi_Program_Ex{Midi_Spec::GS, "Bubble"}},
    {midi_program_ex_id(0x5, 00, 0x7c), Midi_Program_Ex{Midi_Spec::GS, "Windchime"}},
    {midi_program_ex_id(0x5, 00, 0x7d), Midi_Program_Ex{Midi_Spec::GS, "Siren"}},
    {midi_program_ex_id(0x5, 00, 0x7e), Midi_Program_Ex{Midi_Spec::GS, "Footsteps"}},
    {midi_program_ex_id(0x6, 00, 0x7d), Midi_Program_Ex{Midi_Spec::GS, "Train"}},
    {midi_program_ex_id(0x7, 00, 0x7d), Midi_Program_Ex{Midi_Spec::GS, "Jetplane"}},
    {midi_program_ex_id(0x8, 00, 00), Midi_Program_Ex{Midi_Spec::GS, "Piano 1w"}},
    {midi_program_ex_id(0x8, 00, 0x1), Midi_Program_Ex{Midi_Spec::GS, "Piano 2w"}},
    {midi_program_ex_id(0x8, 00, 0x2), Midi_Program_Ex{Midi_Spec::GS, "Piano 3w"}},
    {midi_program_ex_id(0x8, 00, 0x3), Midi_Program_Ex{Midi_Spec::GS, "Honky-tonk w/Old Upright"}},
    {midi_program_ex_id(0x8, 00, 0x4), Midi_Program_Ex{Midi_Spec::GS, "Detuned EP 1"}},
    {midi_program_ex_id(0x8, 00, 0x5), Midi_Program_Ex{Midi_Spec::GS, "Detuned EP 2"}},
    {midi_program_ex_id(0x8, 00, 0x6), Midi_Program_Ex{Midi_Spec::GS, "Coupled Hps."}},
    {midi_program_ex_id(0x8, 00, 0xb), Midi_Program_Ex{Midi_Spec::GS, "Vib.w"}},
    {midi_program_ex_id(0x8, 00, 0xc), Midi_Program_Ex{Midi_Spec::GS, "Marimba w"}},
    {midi_program_ex_id(0x8, 00, 0xe), Midi_Program_Ex{Midi_Spec::GS, "Church Bell"}},
    {midi_program_ex_id(0x8, 00, 0x10), Midi_Program_Ex{Midi_Spec::GS, "Detuned Or.1"}},
    {midi_program_ex_id(0x8, 00, 0x11), Midi_Program_Ex{Midi_Spec::GS, "Detuned Or.2"}},
    {midi_program_ex_id(0x8, 00, 0x13), Midi_Program_Ex{Midi_Spec::GS, "Church Org.2"}},
    {midi_program_ex_id(0x8, 00, 0x15), Midi_Program_Ex{Midi_Spec::GS, "Accordion It"}},
    {midi_program_ex_id(0x8, 00, 0x18), Midi_Program_Ex{Midi_Spec::GS, "Ukulele"}},
    {midi_program_ex_id(0x8, 00, 0x19), Midi_Program_Ex{Midi_Spec::GS, "12-str Guitar"}},
    {midi_program_ex_id(0x8, 00, 0x1a), Midi_Program_Ex{Midi_Spec::GS, "Hawaiian Gt./Pedal Steel"}},
    {midi_program_ex_id(0x8, 00, 0x1b), Midi_Program_Ex{Midi_Spec::GS, "Chorus Gt."}},
    {midi_program_ex_id(0x8, 00, 0x1c), Midi_Program_Ex{Midi_Spec::GS, "Funk Gt/Funk Pop"}},
    {midi_program_ex_id(0x8, 00, 0x1e), Midi_Program_Ex{Midi_Spec::GS, "Feedback Gt."}},
    {midi_program_ex_id(0x8, 00, 0x1f), Midi_Program_Ex{Midi_Spec::GS, "Gt.Feedback"}},
    {midi_program_ex_id(0x8, 00, 0x26), Midi_Program_Ex{Midi_Spec::GS, "Synth Bass 3/Acid Bass"}},
    {midi_program_ex_id(0x8, 00, 0x27), Midi_Program_Ex{Midi_Spec::GS, "Synth Bass 4/Beef FM Bass"}},
    {midi_program_ex_id(0x8, 00, 0x28), Midi_Program_Ex{Midi_Spec::GS, "Slow Violin"}},
    {midi_program_ex_id(0x8, 00, 0x30), Midi_Program_Ex{Midi_Spec::GS, "Orchestra"}},
    {midi_program_ex_id(0x8, 00, 0x32), Midi_Program_Ex{Midi_Spec::GS, "Syn.Strings 3"}},
    {midi_program_ex_id(0x8, 00, 0x3d), Midi_Program_Ex{Midi_Spec::GS, "Brass 2"}},
    {midi_program_ex_id(0x8, 00, 0x3e), Midi_Program_Ex{Midi_Spec::GS, "Synth Brass 3"}},
    {midi_program_ex_id(0x8, 00, 0x3f), Midi_Program_Ex{Midi_Spec::GS, "Synth Brass 4"}},
    {midi_program_ex_id(0x8, 00, 0x50), Midi_Program_Ex{Midi_Spec::GS, "Sine Wave"}},
    {midi_program_ex_id(0x8, 00, 0x51), Midi_Program_Ex{Midi_Spec::GS, "Doctor Solo"}},
    {midi_program_ex_id(0x8, 00, 0x6b), Midi_Program_Ex{Midi_Spec::GS, "Taisho Koto"}},
    {midi_program_ex_id(0x8, 00, 0x73), Midi_Program_Ex{Midi_Spec::GS, "Castanets"}},
    {midi_program_ex_id(0x8, 00, 0x74), Midi_Program_Ex{Midi_Spec::GS, "Concert Bass Drum"}},
    {midi_program_ex_id(0x8, 00, 0x75), Midi_Program_Ex{Midi_Spec::GS, "Melo. Tom 2"}},
    {midi_program_ex_id(0x8, 00, 0x76), Midi_Program_Ex{Midi_Spec::GS, "808 Tom"}},
    {midi_program_ex_id(0x8, 00, 0x7d), Midi_Program_Ex{Midi_Spec::GS, "Starship"}},
    {midi_program_ex_id(0x9, 00, 0xe), Midi_Program_Ex{Midi_Spec::GS, "Carillon"}},
    {midi_program_ex_id(0x9, 00, 0x76), Midi_Program_Ex{Midi_Spec::GS, "Elec Perc"}},
    {midi_program_ex_id(0x9, 00, 0x7d), Midi_Program_Ex{Midi_Spec::GS, "Burst Noise"}},
    {midi_program_ex_id(0x10, 00, 00), Midi_Program_Ex{Midi_Spec::GS, "Piano 1d"}},
    {midi_program_ex_id(0x10, 00, 0x4), Midi_Program_Ex{Midi_Spec::GS, "E.Piano 1w"}},
    {midi_program_ex_id(0x10, 00, 0x5), Midi_Program_Ex{Midi_Spec::GS, "E.Piano 2w/Soft FM EP"}},
    {midi_program_ex_id(0x10, 00, 0x6), Midi_Program_Ex{Midi_Spec::GS, "Harpsi.w"}},
    {midi_program_ex_id(0x10, 00, 0x10), Midi_Program_Ex{Midi_Spec::GS, "60's Organ 1"}},
    {midi_program_ex_id(0x10, 00, 0x13), Midi_Program_Ex{Midi_Spec::GS, "Church Org.3"}},
    {midi_program_ex_id(0x10, 00, 0x18), Midi_Program_Ex{Midi_Spec::GS, "Nylon Gt.o"}},
    {midi_program_ex_id(0x10, 00, 0x19), Midi_Program_Ex{Midi_Spec::GS, "Mandolin"}},
    {midi_program_ex_id(0x10, 00, 0x1c), Midi_Program_Ex{Midi_Spec::GS, "Funk Gt.2"}},
    {midi_program_ex_id(0x10, 00, 0x27), Midi_Program_Ex{Midi_Spec::GS, "Rubber Bass"}},
    {midi_program_ex_id(0x10, 00, 0x3e), Midi_Program_Ex{Midi_Spec::GS, "Analog Brass1/Octave Brass"}},
    {midi_program_ex_id(0x10, 00, 0x3f), Midi_Program_Ex{Midi_Spec::GS, "Analog Brass 2/Velo Brass 1"}},
    {midi_program_ex_id(0x18, 00, 0x4), Midi_Program_Ex{Midi_Spec::GS, "60's E.Piano"}},
    {midi_program_ex_id(0x18, 00, 0x6), Midi_Program_Ex{Midi_Spec::GS, "Harpsi.o"}},
    {midi_program_ex_id(0x20, 00, 0x10), Midi_Program_Ex{Midi_Spec::GS, "Organ 4"}},
    {midi_program_ex_id(0x20, 00, 0x11), Midi_Program_Ex{Midi_Spec::GS, "Organ 5"}},
    {midi_program_ex_id(0x20, 00, 0x18), Midi_Program_Ex{Midi_Spec::GS, "Nylon Gt.2"}},
    {midi_program_ex_id(0x20, 00, 0x34), Midi_Program_Ex{Midi_Spec::GS, "Choir Aahs 2"}},
    {midi_program_ex_id(0x1, 00, 0x2), Midi_Program_Ex{Midi_Spec::SC88, "EG+Rhodes1"}},
    {midi_program_ex_id(0x1, 00, 0xb), Midi_Program_Ex{Midi_Spec::SC88, "Hard Vibe"}},
    {midi_program_ex_id(0x1, 00, 0xf), Midi_Program_Ex{Midi_Spec::SC88, "Santur 2"}},
    {midi_program_ex_id(0x1, 00, 0x10), Midi_Program_Ex{Midi_Spec::SC88, "Organ 101"}},
    {midi_program_ex_id(0x1, 00, 0x11), Midi_Program_Ex{Midi_Spec::SC88, "Organ 201"}},
    {midi_program_ex_id(0x1, 00, 0x16), Midi_Program_Ex{Midi_Spec::SC88, "Harmonica 2"}},
    {midi_program_ex_id(0x1, 00, 0x1a), Midi_Program_Ex{Midi_Spec::SC88, "Mellow Gt."}},
    {midi_program_ex_id(0x1, 00, 0x1c), Midi_Program_Ex{Midi_Spec::SC88, "Muted Dis.Gt"}},
    {midi_program_ex_id(0x1, 00, 0x1e), Midi_Program_Ex{Midi_Spec::SC88, "Dist.Gt 2"}},
    {midi_program_ex_id(0x1, 00, 0x21), Midi_Program_Ex{Midi_Spec::SC88, "Fingered Bs2"}},
    {midi_program_ex_id(0x1, 00, 0x23), Midi_Program_Ex{Midi_Spec::SC88, "Fretless Bs2"}},
    {midi_program_ex_id(0x1, 00, 0x27), Midi_Program_Ex{Midi_Spec::SC88, "Synth Bass 201"}},
    {midi_program_ex_id(0x1, 00, 0x30), Midi_Program_Ex{Midi_Spec::SC88, "Strings 2"}},
    {midi_program_ex_id(0x1, 00, 0x31), Midi_Program_Ex{Midi_Spec::SC88, "SlowStrings2"}},
    {midi_program_ex_id(0x1, 00, 0x32), Midi_Program_Ex{Midi_Spec::SC88, "OB Strings"}},
    {midi_program_ex_id(0x1, 00, 0x38), Midi_Program_Ex{Midi_Spec::SC88, "Trumpet 2"}},
    {midi_program_ex_id(0x1, 00, 0x3a), Midi_Program_Ex{Midi_Spec::SC88, "Tuba 2"}},
    {midi_program_ex_id(0x1, 00, 0x3e), Midi_Program_Ex{Midi_Spec::SC88, "Poly Brass"}},
    {midi_program_ex_id(0x1, 00, 0x3f), Midi_Program_Ex{Midi_Spec::SC88, "Soft Brass"}},
    {midi_program_ex_id(0x1, 00, 0x52), Midi_Program_Ex{Midi_Spec::SC88, "Vent Synth"}},
    {midi_program_ex_id(0x1, 00, 0x56), Midi_Program_Ex{Midi_Spec::SC88, "Big Fives"}},
    {midi_program_ex_id(0x1, 00, 0x57), Midi_Program_Ex{Midi_Spec::SC88, "Big & Raw"}},
    {midi_program_ex_id(0x1, 00, 0x58), Midi_Program_Ex{Midi_Spec::SC88, "Fantasia 2"}},
    {midi_program_ex_id(0x1, 00, 0x59), Midi_Program_Ex{Midi_Spec::SC88, "Thick Pad"}},
    {midi_program_ex_id(0x1, 00, 0x5a), Midi_Program_Ex{Midi_Spec::SC88, "80's PolySyn"}},
    {midi_program_ex_id(0x1, 00, 0x5b), Midi_Program_Ex{Midi_Spec::SC88, "Heaven II"}},
    {midi_program_ex_id(0x1, 00, 0x5d), Midi_Program_Ex{Midi_Spec::SC88, "Tine Pad"}},
    {midi_program_ex_id(0x1, 00, 0x5f), Midi_Program_Ex{Midi_Spec::SC88, "Polar Pad"}},
    {midi_program_ex_id(0x1, 00, 0x60), Midi_Program_Ex{Midi_Spec::SC88, "Harmo Rain"}},
    {midi_program_ex_id(0x1, 00, 0x61), Midi_Program_Ex{Midi_Spec::SC88, "Ancestral"}},
    {midi_program_ex_id(0x1, 00, 0x63), Midi_Program_Ex{Midi_Spec::SC88, "Warm Atmos"}},
    {midi_program_ex_id(0x1, 00, 0x65), Midi_Program_Ex{Midi_Spec::SC88, "Goblinson"}},
    {midi_program_ex_id(0x1, 00, 0x67), Midi_Program_Ex{Midi_Spec::SC88, "Star Theme 2"}},
    {midi_program_ex_id(0x1, 00, 0x69), Midi_Program_Ex{Midi_Spec::SC88, "Muted Banjo"}},
    {midi_program_ex_id(0x1, 00, 0x6a), Midi_Program_Ex{Midi_Spec::SC88, "Tsugaru"}},
    {midi_program_ex_id(0x1, 00, 0x6f), Midi_Program_Ex{Midi_Spec::SC88, "Shanai 2"}},
    {midi_program_ex_id(0x1, 00, 0x75), Midi_Program_Ex{Midi_Spec::SC88, "Real Tom"}},
    {midi_program_ex_id(0x1, 00, 0x77), Midi_Program_Ex{Midi_Spec::SC88, "Reverse Cym2"}},
    {midi_program_ex_id(0x2, 00, 0x2), Midi_Program_Ex{Midi_Spec::SC88, "EG+Rhodes2"}},
    {midi_program_ex_id(0x2, 00, 0x1e), Midi_Program_Ex{Midi_Spec::SC88, "Dazed Guitar"}},
    {midi_program_ex_id(0x2, 00, 0x21), Midi_Program_Ex{Midi_Spec::SC88, "Jazz Bass"}},
    {midi_program_ex_id(0x2, 00, 0x23), Midi_Program_Ex{Midi_Spec::SC88, "Fretless Bs3"}},
    {midi_program_ex_id(0x2, 00, 0x27), Midi_Program_Ex{Midi_Spec::SC88, "Modular Bass"}},
    {midi_program_ex_id(0x2, 00, 0x50), Midi_Program_Ex{Midi_Spec::SC88, "Hollow Mini"}},
    {midi_program_ex_id(0x2, 00, 0x51), Midi_Program_Ex{Midi_Spec::SC88, "Pulse Saw"}},
    {midi_program_ex_id(0x2, 00, 0x52), Midi_Program_Ex{Midi_Spec::SC88, "Pure PanLead"}},
    {midi_program_ex_id(0x2, 00, 0x57), Midi_Program_Ex{Midi_Spec::SC88, "Fat & Perky"}},
    {midi_program_ex_id(0x2, 00, 0x59), Midi_Program_Ex{Midi_Spec::SC88, "Horn Pad"}},
    {midi_program_ex_id(0x2, 00, 0x5d), Midi_Program_Ex{Midi_Spec::SC88, "Panner Pad"}},
    {midi_program_ex_id(0x2, 00, 0x60), Midi_Program_Ex{Midi_Spec::SC88, "African Wood"}},
    {midi_program_ex_id(0x2, 00, 0x61), Midi_Program_Ex{Midi_Spec::SC88, "Prologue"}},
    {midi_program_ex_id(0x2, 00, 0x62), Midi_Program_Ex{Midi_Spec::SC88, "Soft Crystal"}},
    {midi_program_ex_id(0x2, 00, 0x63), Midi_Program_Ex{Midi_Spec::SC88, "Nylon Harp"}},
    {midi_program_ex_id(0x2, 00, 0x65), Midi_Program_Ex{Midi_Spec::SC88, "50's Sci-Fi"}},
    {midi_program_ex_id(0x2, 00, 0x68), Midi_Program_Ex{Midi_Spec::SC88, "Detune Sitar"}},
    {midi_program_ex_id(0x3, 00, 0x23), Midi_Program_Ex{Midi_Spec::SC88, "Fretless Bs4"}},
    {midi_program_ex_id(0x3, 00, 0x27), Midi_Program_Ex{Midi_Spec::SC88, "Seq Bass"}},
    {midi_program_ex_id(0x3, 00, 0x50), Midi_Program_Ex{Midi_Spec::SC88, "Mellow FM"}},
    {midi_program_ex_id(0x3, 00, 0x51), Midi_Program_Ex{Midi_Spec::SC88, "Feline GR"}},
    {midi_program_ex_id(0x3, 00, 0x59), Midi_Program_Ex{Midi_Spec::SC88, "RotaryString"}},
    {midi_program_ex_id(0x3, 00, 0x62), Midi_Program_Ex{Midi_Spec::SC88, "Round Glock"}},
    {midi_program_ex_id(0x3, 00, 0x63), Midi_Program_Ex{Midi_Spec::SC88, "Harpvox"}},
    {midi_program_ex_id(0x3, 00, 0x66), Midi_Program_Ex{Midi_Spec::SC88, "Echo Pan 2"}},
    {midi_program_ex_id(0x3, 00, 0x78), Midi_Program_Ex{Midi_Spec::SC88, "Gt.CutNoise2"}},
    {midi_program_ex_id(0x4, 00, 0x50), Midi_Program_Ex{Midi_Spec::SC88, "CC Solo"}},
    {midi_program_ex_id(0x4, 00, 0x51), Midi_Program_Ex{Midi_Spec::SC88, "Big Lead"}},
    {midi_program_ex_id(0x4, 00, 0x59), Midi_Program_Ex{Midi_Spec::SC88, "Soft Pad"}},
    {midi_program_ex_id(0x4, 00, 0x62), Midi_Program_Ex{Midi_Spec::SC88, "Loud Glock"}},
    {midi_program_ex_id(0x4, 00, 0x63), Midi_Program_Ex{Midi_Spec::SC88, "HollowReleas"}},
    {midi_program_ex_id(0x4, 00, 0x66), Midi_Program_Ex{Midi_Spec::SC88, "Big Panner"}},
    {midi_program_ex_id(0x4, 00, 0x78), Midi_Program_Ex{Midi_Spec::SC88, "Dist.CutNoise"}},
    {midi_program_ex_id(0x4, 00, 0x7b), Midi_Program_Ex{Midi_Spec::SC88, "Kitty"}},
    {midi_program_ex_id(0x5, 00, 0x23), Midi_Program_Ex{Midi_Spec::SC88, "Mr.Smooth"}},
    {midi_program_ex_id(0x5, 00, 0x50), Midi_Program_Ex{Midi_Spec::SC88, "Shmoog"}},
    {midi_program_ex_id(0x5, 00, 0x51), Midi_Program_Ex{Midi_Spec::SC88, "Velo Lead"}},
    {midi_program_ex_id(0x5, 00, 0x62), Midi_Program_Ex{Midi_Spec::SC88, "GlockenChime"}},
    {midi_program_ex_id(0x5, 00, 0x63), Midi_Program_Ex{Midi_Spec::SC88, "Nylon+Rhodes"}},
    {midi_program_ex_id(0x5, 00, 0x66), Midi_Program_Ex{Midi_Spec::SC88, "Reso Panner"}},
    {midi_program_ex_id(0x5, 00, 0x78), Midi_Program_Ex{Midi_Spec::SC88, "Bass Slide"}},
    {midi_program_ex_id(0x5, 00, 0x7b), Midi_Program_Ex{Midi_Spec::SC88, "Growl"}},
    {midi_program_ex_id(0x6, 00, 0x50), Midi_Program_Ex{Midi_Spec::SC88, "LM Square"}},
    {midi_program_ex_id(0x6, 00, 0x51), Midi_Program_Ex{Midi_Spec::SC88, "GR-300"}},
    {midi_program_ex_id(0x6, 00, 0x62), Midi_Program_Ex{Midi_Spec::SC88, "Clear Bells"}},
    {midi_program_ex_id(0x6, 00, 0x63), Midi_Program_Ex{Midi_Spec::SC88, "Ambient Pad"}},
    {midi_program_ex_id(0x6, 00, 0x66), Midi_Program_Ex{Midi_Spec::SC88, "Water Piano"}},
    {midi_program_ex_id(0x6, 00, 0x78), Midi_Program_Ex{Midi_Spec::SC88, "Pick Scrape"}},
    {midi_program_ex_id(0x6, 00, 0x7e), Midi_Program_Ex{Midi_Spec::SC88, "Applause 2"}},
    {midi_program_ex_id(0x7, 00, 0x51), Midi_Program_Ex{Midi_Spec::SC88, "LA Saw"}},
    {midi_program_ex_id(0x7, 00, 0x62), Midi_Program_Ex{Midi_Spec::SC88, "ChristmasBel"}},
    {midi_program_ex_id(0x7, 00, 0x7c), Midi_Program_Ex{Midi_Spec::SC88, "Scratch 2"}},
    {midi_program_ex_id(0x8, 00, 0xf), Midi_Program_Ex{Midi_Spec::SC88, "Cimbalom"}},
    {midi_program_ex_id(0x8, 00, 0x12), Midi_Program_Ex{Midi_Spec::SC88, "Rotary Org."}},
    {midi_program_ex_id(0x8, 00, 0x22), Midi_Program_Ex{Midi_Spec::SC88, "Mute PickBs."}},
    {midi_program_ex_id(0x8, 00, 0x24), Midi_Program_Ex{Midi_Spec::SC88, "Reso Slap"}},
    {midi_program_ex_id(0x8, 00, 0x2c), Midi_Program_Ex{Midi_Spec::SC88, "Slow Tremolo"}},
    {midi_program_ex_id(0x8, 00, 0x31), Midi_Program_Ex{Midi_Spec::SC88, "Legato Str."}},
    {midi_program_ex_id(0x8, 00, 0x34), Midi_Program_Ex{Midi_Spec::SC88, "St.Choir"}},
    {midi_program_ex_id(0x8, 00, 0x36), Midi_Program_Ex{Midi_Spec::SC88, "Syn.Voice"}},
    {midi_program_ex_id(0x8, 00, 0x37), Midi_Program_Ex{Midi_Spec::SC88, "Impact Hit"}},
    {midi_program_ex_id(0x8, 00, 0x38), Midi_Program_Ex{Midi_Spec::SC88, "Flugel Horn"}},
    {midi_program_ex_id(0x8, 00, 0x3c), Midi_Program_Ex{Midi_Spec::SC88, "Fr.Horn Solo"}},
    {midi_program_ex_id(0x8, 00, 0x41), Midi_Program_Ex{Midi_Spec::SC88, "Hyper Alto"}},
    {midi_program_ex_id(0x8, 00, 0x42), Midi_Program_Ex{Midi_Spec::SC88, "BreathyTenor"}},
    {midi_program_ex_id(0x8, 00, 0x47), Midi_Program_Ex{Midi_Spec::SC88, "Bs.Clarinet"}},
    {midi_program_ex_id(0x8, 00, 0x4b), Midi_Program_Ex{Midi_Spec::SC88, "Kawala"}},
    {midi_program_ex_id(0x8, 00, 0x54), Midi_Program_Ex{Midi_Spec::SC88, "Dist.Lead"}},
    {midi_program_ex_id(0x8, 00, 0x5f), Midi_Program_Ex{Midi_Spec::SC88, "Converge"}},
    {midi_program_ex_id(0x8, 00, 0x60), Midi_Program_Ex{Midi_Spec::SC88, "Clavi Pad"}},
    {midi_program_ex_id(0x8, 00, 0x61), Midi_Program_Ex{Midi_Spec::SC88, "Rave"}},
    {midi_program_ex_id(0x8, 00, 0x62), Midi_Program_Ex{Midi_Spec::SC88, "Vibra Bells"}},
    {midi_program_ex_id(0x8, 00, 0x68), Midi_Program_Ex{Midi_Spec::SC88, "Tambra"}},
    {midi_program_ex_id(0x8, 00, 0x69), Midi_Program_Ex{Midi_Spec::SC88, "Rabab"}},
    {midi_program_ex_id(0x8, 00, 0x6f), Midi_Program_Ex{Midi_Spec::SC88, "Pungi"}},
    {midi_program_ex_id(0x8, 00, 0x70), Midi_Program_Ex{Midi_Spec::SC88, "Bonang"}},
    {midi_program_ex_id(0x8, 00, 0x71), Midi_Program_Ex{Midi_Spec::SC88, "Atarigane"}},
    {midi_program_ex_id(0x8, 00, 0x77), Midi_Program_Ex{Midi_Spec::SC88, "Rev.Snare 1"}},
    {midi_program_ex_id(0x9, 00, 0x10), Midi_Program_Ex{Midi_Spec::SC88, "Organ 109"}},
    {midi_program_ex_id(0x9, 00, 0x19), Midi_Program_Ex{Midi_Spec::SC88, "Nylon+Steel"}},
    {midi_program_ex_id(0x9, 00, 0x1e), Midi_Program_Ex{Midi_Spec::SC88, "Feedback Gt2"}},
    {midi_program_ex_id(0x9, 00, 0x27), Midi_Program_Ex{Midi_Spec::SC88, "X Wire Bass"}},
    {midi_program_ex_id(0x9, 00, 0x2c), Midi_Program_Ex{Midi_Spec::SC88, "Suspense Str"}},
    {midi_program_ex_id(0x9, 00, 0x30), Midi_Program_Ex{Midi_Spec::SC88, "Orchestra 2"}},
    {midi_program_ex_id(0x9, 00, 0x31), Midi_Program_Ex{Midi_Spec::SC88, "Warm Strings"}},
    {midi_program_ex_id(0x9, 00, 0x34), Midi_Program_Ex{Midi_Spec::SC88, "Mello Choir"}},
    {midi_program_ex_id(0x9, 00, 0x37), Midi_Program_Ex{Midi_Spec::SC88, "Philly Hit"}},
    {midi_program_ex_id(0x9, 00, 0x3e), Midi_Program_Ex{Midi_Spec::SC88, "Quack Brass"}},
    {midi_program_ex_id(0x9, 00, 0x5f), Midi_Program_Ex{Midi_Spec::SC88, "Shwimmer"}},
    {midi_program_ex_id(0x9, 00, 0x62), Midi_Program_Ex{Midi_Spec::SC88, "Digi Bells"}},
    {midi_program_ex_id(0x9, 00, 0x70), Midi_Program_Ex{Midi_Spec::SC88, "Gender"}},
    {midi_program_ex_id(0x9, 00, 0x75), Midi_Program_Ex{Midi_Spec::SC88, "Rock Tom"}},
    {midi_program_ex_id(0x9, 00, 0x77), Midi_Program_Ex{Midi_Spec::SC88, "Rev.Snare 2"}},
    {midi_program_ex_id(0xa, 00, 0x26), Midi_Program_Ex{Midi_Spec::SC88, "Tekno Bass"}},
    {midi_program_ex_id(0xa, 00, 0x30), Midi_Program_Ex{Midi_Spec::SC88, "Tremolo Orch"}},
    {midi_program_ex_id(0xa, 00, 0x31), Midi_Program_Ex{Midi_Spec::SC88, "St.Slow Str."}},
    {midi_program_ex_id(0xa, 00, 0x37), Midi_Program_Ex{Midi_Spec::SC88, "Double Hit"}},
    {midi_program_ex_id(0xa, 00, 0x5f), Midi_Program_Ex{Midi_Spec::SC88, "Celestial Pd"}},
    {midi_program_ex_id(0xa, 00, 0x70), Midi_Program_Ex{Midi_Spec::SC88, "Gamelan Gong"}},
    {midi_program_ex_id(0xb, 00, 0x30), Midi_Program_Ex{Midi_Spec::SC88, "Choir Str."}},
    {midi_program_ex_id(0xb, 00, 0x70), Midi_Program_Ex{Midi_Spec::SC88, "St.Gamelan"}},
    {midi_program_ex_id(0x10, 00, 0xc), Midi_Program_Ex{Midi_Spec::SC88, "Barafon"}},
    {midi_program_ex_id(0x10, 00, 0x12), Midi_Program_Ex{Midi_Spec::SC88, "Rotary Org.S"}},
    {midi_program_ex_id(0x10, 00, 0x1e), Midi_Program_Ex{Midi_Spec::SC88, "Power Guitar"}},
    {midi_program_ex_id(0x10, 00, 0x1f), Midi_Program_Ex{Midi_Spec::SC88, "Ac.Gt.Harmonx"}},
    {midi_program_ex_id(0x10, 00, 0x26), Midi_Program_Ex{Midi_Spec::SC88, "Reso SH Bass"}},
    {midi_program_ex_id(0x10, 00, 0x30), Midi_Program_Ex{Midi_Spec::SC88, "St.Strings"}},
    {midi_program_ex_id(0x10, 00, 0x37), Midi_Program_Ex{Midi_Spec::SC88, "Lo Fi Rave"}},
    {midi_program_ex_id(0x10, 00, 0x3c), Midi_Program_Ex{Midi_Spec::SC88, "Horn Orch"}},
    {midi_program_ex_id(0x10, 00, 0x3d), Midi_Program_Ex{Midi_Spec::SC88, "Brass Fall"}},
    {midi_program_ex_id(0x10, 00, 0x51), Midi_Program_Ex{Midi_Spec::SC88, "Waspy Synth"}},
    {midi_program_ex_id(0x10, 00, 0x62), Midi_Program_Ex{Midi_Spec::SC88, "Choral Bells"}},
    {midi_program_ex_id(0x10, 00, 0x68), Midi_Program_Ex{Midi_Spec::SC88, "Tamboura"}},
    {midi_program_ex_id(0x10, 00, 0x69), Midi_Program_Ex{Midi_Spec::SC88, "Gopichant"}},
    {midi_program_ex_id(0x10, 00, 0x6b), Midi_Program_Ex{Midi_Spec::SC88, "Kanoon"}},
    {midi_program_ex_id(0x10, 00, 0x6f), Midi_Program_Ex{Midi_Spec::SC88, "Hichiriki"}},
    {midi_program_ex_id(0x10, 00, 0x70), Midi_Program_Ex{Midi_Spec::SC88, "RAMA Cymbal"}},
    {midi_program_ex_id(0x10, 00, 0x77), Midi_Program_Ex{Midi_Spec::SC88, "Rev.Kick 1"}},
    {midi_program_ex_id(0x11, 00, 0xc), Midi_Program_Ex{Midi_Spec::SC88, "Barafon 2"}},
    {midi_program_ex_id(0x11, 00, 0x10), Midi_Program_Ex{Midi_Spec::SC88, "60's Organ 2"}},
    {midi_program_ex_id(0x11, 00, 0x1e), Midi_Program_Ex{Midi_Spec::SC88, "Power Gt.2"}},
    {midi_program_ex_id(0x11, 00, 0x27), Midi_Program_Ex{Midi_Spec::SC88, "SH101 Bass 1"}},
    {midi_program_ex_id(0x11, 00, 0x3f), Midi_Program_Ex{Midi_Spec::SC88, "Velo Brass 2"}},
    {midi_program_ex_id(0x11, 00, 0x62), Midi_Program_Ex{Midi_Spec::SC88, "Air Bells"}},
    {midi_program_ex_id(0x11, 00, 0x77), Midi_Program_Ex{Midi_Spec::SC88, "Rev.ConBD"}},
    {midi_program_ex_id(0x12, 00, 0x10), Midi_Program_Ex{Midi_Spec::SC88, "60's Organ 3"}},
    {midi_program_ex_id(0x12, 00, 0x1e), Midi_Program_Ex{Midi_Spec::SC88, "5th Dist."}},
    {midi_program_ex_id(0x12, 00, 0x27), Midi_Program_Ex{Midi_Spec::SC88, "SH101 Bass 2"}},
    {midi_program_ex_id(0x12, 00, 0x62), Midi_Program_Ex{Midi_Spec::SC88, "Bell Harp"}},
    {midi_program_ex_id(0x13, 00, 0x27), Midi_Program_Ex{Midi_Spec::SC88, "Smooth Bass"}},
    {midi_program_ex_id(0x13, 00, 0x62), Midi_Program_Ex{Midi_Spec::SC88, "Gamelimba"}},
    {midi_program_ex_id(0x18, 00, 0x5), Midi_Program_Ex{Midi_Spec::SC88, "Hard FM EP"}},
    {midi_program_ex_id(0x18, 00, 0xc), Midi_Program_Ex{Midi_Spec::SC88, "Log Drum"}},
    {midi_program_ex_id(0x18, 00, 0x10), Midi_Program_Ex{Midi_Spec::SC88, "Cheese Organ"}},
    {midi_program_ex_id(0x18, 00, 0x12), Midi_Program_Ex{Midi_Spec::SC88, "Rotary Org.F"}},
    {midi_program_ex_id(0x18, 00, 0x13), Midi_Program_Ex{Midi_Spec::SC88, "Organ Flute"}},
    {midi_program_ex_id(0x18, 00, 0x18), Midi_Program_Ex{Midi_Spec::SC88, "Velo Harmnix"}},
    {midi_program_ex_id(0x18, 00, 0x1e), Midi_Program_Ex{Midi_Spec::SC88, "Rock Rhythm"}},
    {midi_program_ex_id(0x18, 00, 0x30), Midi_Program_Ex{Midi_Spec::SC88, "Velo Strings"}},
    {midi_program_ex_id(0x18, 00, 0x38), Midi_Program_Ex{Midi_Spec::SC88, "Bright Tp."}},
    {midi_program_ex_id(0x18, 00, 0x69), Midi_Program_Ex{Midi_Spec::SC88, "Oud"}},
    {midi_program_ex_id(0x18, 00, 0x77), Midi_Program_Ex{Midi_Spec::SC88, "Rev.Tom 1"}},
    {midi_program_ex_id(0x19, 00, 0x4), Midi_Program_Ex{Midi_Spec::SC88, "Hard Rhodes"}},
    {midi_program_ex_id(0x19, 00, 0x1e), Midi_Program_Ex{Midi_Spec::SC88, "Rock Rhythm2"}},
    {midi_program_ex_id(0x19, 00, 0x38), Midi_Program_Ex{Midi_Spec::SC88, "Warm Tp."}},
    {midi_program_ex_id(0x19, 00, 0x77), Midi_Program_Ex{Midi_Spec::SC88, "Rev.Tom 2"}},
    {midi_program_ex_id(0x1a, 00, 0x4), Midi_Program_Ex{Midi_Spec::SC88, "MellowRhodes"}},
    {midi_program_ex_id(0x20, 00, 0x13), Midi_Program_Ex{Midi_Spec::SC88, "Trem.Flute"}},
    {midi_program_ex_id(0x20, 00, 0x19), Midi_Program_Ex{Midi_Spec::SC88, "Steel Gt.2"}},
    {midi_program_ex_id(0x21, 00, 0x10), Midi_Program_Ex{Midi_Spec::SC88, "Even Bar"}},
    {midi_program_ex_id(0x28, 00, 0x10), Midi_Program_Ex{Midi_Spec::SC88, "Organ Bass"}},
    {midi_program_ex_id(0x28, 00, 0x18), Midi_Program_Ex{Midi_Spec::SC88, "Lequint Gt."}},
    {midi_program_ex_id(0x7f, 00, 00), Midi_Program_Ex{Midi_Spec::MT32, "Acou Piano 1"}},
    {midi_program_ex_id(0x7f, 00, 0x1), Midi_Program_Ex{Midi_Spec::MT32, "Acou Piano 2"}},
    {midi_program_ex_id(0x7f, 00, 0x2), Midi_Program_Ex{Midi_Spec::MT32, "Acou Piano 3"}},
    {midi_program_ex_id(0x7f, 00, 0x3), Midi_Program_Ex{Midi_Spec::MT32, "Elec Piano 1"}},
    {midi_program_ex_id(0x7f, 00, 0x4), Midi_Program_Ex{Midi_Spec::MT32, "Elec Piano 2"}},
    {midi_program_ex_id(0x7f, 00, 0x5), Midi_Program_Ex{Midi_Spec::MT32, "Elec Piano 3"}},
    {midi_program_ex_id(0x7f, 00, 0x6), Midi_Program_Ex{Midi_Spec::MT32, "Elec Piano 4"}},
    {midi_program_ex_id(0x7f, 00, 0x7), Midi_Program_Ex{Midi_Spec::MT32, "Honkytonk"}},
    {midi_program_ex_id(0x7f, 00, 0x8), Midi_Program_Ex{Midi_Spec::MT32, "Elec Org 1"}},
    {midi_program_ex_id(0x7f, 00, 0x9), Midi_Program_Ex{Midi_Spec::MT32, "Elec Org 2"}},
    {midi_program_ex_id(0x7f, 00, 0xa), Midi_Program_Ex{Midi_Spec::MT32, "Elec Org 3"}},
    {midi_program_ex_id(0x7f, 00, 0xb), Midi_Program_Ex{Midi_Spec::MT32, "Elec Org 4"}},
    {midi_program_ex_id(0x7f, 00, 0xc), Midi_Program_Ex{Midi_Spec::MT32, "Pipe Org 1"}},
    {midi_program_ex_id(0x7f, 00, 0xd), Midi_Program_Ex{Midi_Spec::MT32, "Pipe Org 2"}},
    {midi_program_ex_id(0x7f, 00, 0xe), Midi_Program_Ex{Midi_Spec::MT32, "Pipe Org 3"}},
    {midi_program_ex_id(0x7f, 00, 0xf), Midi_Program_Ex{Midi_Spec::MT32, "Accordion"}},
    {midi_program_ex_id(0x7f, 00, 0x10), Midi_Program_Ex{Midi_Spec::MT32, "Harpsi 1"}},
    {midi_program_ex_id(0x7f, 00, 0x11), Midi_Program_Ex{Midi_Spec::MT32, "Harpsi 2"}},
    {midi_program_ex_id(0x7f, 00, 0x12), Midi_Program_Ex{Midi_Spec::MT32, "Harpsi 3"}},
    {midi_program_ex_id(0x7f, 00, 0x13), Midi_Program_Ex{Midi_Spec::MT32, "Clavi 1"}},
    {midi_program_ex_id(0x7f, 00, 0x14), Midi_Program_Ex{Midi_Spec::MT32, "Clavi 2"}},
    {midi_program_ex_id(0x7f, 00, 0x15), Midi_Program_Ex{Midi_Spec::MT32, "Clavi 3"}},
    {midi_program_ex_id(0x7f, 00, 0x16), Midi_Program_Ex{Midi_Spec::MT32, "Celesta 1"}},
    {midi_program_ex_id(0x7f, 00, 0x17), Midi_Program_Ex{Midi_Spec::MT32, "Celesta 2"}},
    {midi_program_ex_id(0x7f, 00, 0x18), Midi_Program_Ex{Midi_Spec::MT32, "Syn Brass 1"}},
    {midi_program_ex_id(0x7f, 00, 0x19), Midi_Program_Ex{Midi_Spec::MT32, "Syn Brass 2"}},
    {midi_program_ex_id(0x7f, 00, 0x1a), Midi_Program_Ex{Midi_Spec::MT32, "Syn Brass 3"}},
    {midi_program_ex_id(0x7f, 00, 0x1b), Midi_Program_Ex{Midi_Spec::MT32, "Syn Brass 4"}},
    {midi_program_ex_id(0x7f, 00, 0x1c), Midi_Program_Ex{Midi_Spec::MT32, "Syn Bass 1"}},
    {midi_program_ex_id(0x7f, 00, 0x1d), Midi_Program_Ex{Midi_Spec::MT32, "Syn Bass 2"}},
    {midi_program_ex_id(0x7f, 00, 0x1e), Midi_Program_Ex{Midi_Spec::MT32, "Syn Bass 3"}},
    {midi_program_ex_id(0x7f, 00, 0x1f), Midi_Program_Ex{Midi_Spec::MT32, "Syn Bass 4"}},
    {midi_program_ex_id(0x7f, 00, 0x20), Midi_Program_Ex{Midi_Spec::MT32, "Fantasy"}},
    {midi_program_ex_id(0x7f, 00, 0x21), Midi_Program_Ex{Midi_Spec::MT32, "Harmo Pan"}},
    {midi_program_ex_id(0x7f, 00, 0x22), Midi_Program_Ex{Midi_Spec::MT32, "Chorale"}},
    {midi_program_ex_id(0x7f, 00, 0x23), Midi_Program_Ex{Midi_Spec::MT32, "Glasses"}},
    {midi_program_ex_id(0x7f, 00, 0x24), Midi_Program_Ex{Midi_Spec::MT32, "Soundtrack"}},
    {midi_program_ex_id(0x7f, 00, 0x25), Midi_Program_Ex{Midi_Spec::MT32, "Atmosphere"}},
    {midi_program_ex_id(0x7f, 00, 0x26), Midi_Program_Ex{Midi_Spec::MT32, "Warm Bell"}},
    {midi_program_ex_id(0x7f, 00, 0x27), Midi_Program_Ex{Midi_Spec::MT32, "Funny Vox"}},
    {midi_program_ex_id(0x7f, 00, 0x28), Midi_Program_Ex{Midi_Spec::MT32, "Echo Bell"}},
    {midi_program_ex_id(0x7f, 00, 0x29), Midi_Program_Ex{Midi_Spec::MT32, "Ice Rain"}},
    {midi_program_ex_id(0x7f, 00, 0x2a), Midi_Program_Ex{Midi_Spec::MT32, "Oboe 2001"}},
    {midi_program_ex_id(0x7f, 00, 0x2b), Midi_Program_Ex{Midi_Spec::MT32, "Echo Pan"}},
    {midi_program_ex_id(0x7f, 00, 0x2c), Midi_Program_Ex{Midi_Spec::MT32, "Doctor Solo"}},
    {midi_program_ex_id(0x7f, 00, 0x2d), Midi_Program_Ex{Midi_Spec::MT32, "School Daze"}},
    {midi_program_ex_id(0x7f, 00, 0x2e), Midi_Program_Ex{Midi_Spec::MT32, "Bellsinger"}},
    {midi_program_ex_id(0x7f, 00, 0x2f), Midi_Program_Ex{Midi_Spec::MT32, "Square Wave"}},
    {midi_program_ex_id(0x7f, 00, 0x30), Midi_Program_Ex{Midi_Spec::MT32, "Str Sect 1"}},
    {midi_program_ex_id(0x7f, 00, 0x31), Midi_Program_Ex{Midi_Spec::MT32, "Str Sect 2"}},
    {midi_program_ex_id(0x7f, 00, 0x32), Midi_Program_Ex{Midi_Spec::MT32, "Str Sect 3"}},
    {midi_program_ex_id(0x7f, 00, 0x33), Midi_Program_Ex{Midi_Spec::MT32, "Pizzicato"}},
    {midi_program_ex_id(0x7f, 00, 0x34), Midi_Program_Ex{Midi_Spec::MT32, "Violin 1"}},
    {midi_program_ex_id(0x7f, 00, 0x35), Midi_Program_Ex{Midi_Spec::MT32, "Violin 2"}},
    {midi_program_ex_id(0x7f, 00, 0x36), Midi_Program_Ex{Midi_Spec::MT32, "Cello 1"}},
    {midi_program_ex_id(0x7f, 00, 0x37), Midi_Program_Ex{Midi_Spec::MT32, "Cello 2"}},
    {midi_program_ex_id(0x7f, 00, 0x38), Midi_Program_Ex{Midi_Spec::MT32, "Contrabass"}},
    {midi_program_ex_id(0x7f, 00, 0x39), Midi_Program_Ex{Midi_Spec::MT32, "Harp 1"}},
    {midi_program_ex_id(0x7f, 00, 0x3a), Midi_Program_Ex{Midi_Spec::MT32, "Harp 2"}},
    {midi_program_ex_id(0x7f, 00, 0x3b), Midi_Program_Ex{Midi_Spec::MT32, "Guitar 1"}},
    {midi_program_ex_id(0x7f, 00, 0x3c), Midi_Program_Ex{Midi_Spec::MT32, "Guitar 2"}},
    {midi_program_ex_id(0x7f, 00, 0x3d), Midi_Program_Ex{Midi_Spec::MT32, "Elec Gtr 1"}},
    {midi_program_ex_id(0x7f, 00, 0x3e), Midi_Program_Ex{Midi_Spec::MT32, "Elect Gtr 2"}},
    {midi_program_ex_id(0x7f, 00, 0x3f), Midi_Program_Ex{Midi_Spec::MT32, "Sitar"}},
    {midi_program_ex_id(0x7f, 00, 0x40), Midi_Program_Ex{Midi_Spec::MT32, "Acou Bass 1"}},
    {midi_program_ex_id(0x7f, 00, 0x41), Midi_Program_Ex{Midi_Spec::MT32, "Acou Bass 2"}},
    {midi_program_ex_id(0x7f, 00, 0x42), Midi_Program_Ex{Midi_Spec::MT32, "Elec Bass 1"}},
    {midi_program_ex_id(0x7f, 00, 0x43), Midi_Program_Ex{Midi_Spec::MT32, "Elec Bass 2"}},
    {midi_program_ex_id(0x7f, 00, 0x44), Midi_Program_Ex{Midi_Spec::MT32, "Slap Bass 1"}},
    {midi_program_ex_id(0x7f, 00, 0x45), Midi_Program_Ex{Midi_Spec::MT32, "Slap Bass 2"}},
    {midi_program_ex_id(0x7f, 00, 0x46), Midi_Program_Ex{Midi_Spec::MT32, "Fretless 1"}},
    {midi_program_ex_id(0x7f, 00, 0x47), Midi_Program_Ex{Midi_Spec::MT32, "Fretless 2"}},
    {midi_program_ex_id(0x7f, 00, 0x48), Midi_Program_Ex{Midi_Spec::MT32, "Flute 1"}},
    {midi_program_ex_id(0x7f, 00, 0x49), Midi_Program_Ex{Midi_Spec::MT32, "Flute 2"}},
    {midi_program_ex_id(0x7f, 00, 0x4a), Midi_Program_Ex{Midi_Spec::MT32, "Piccolo 1"}},
    {midi_program_ex_id(0x7f, 00, 0x4b), Midi_Program_Ex{Midi_Spec::MT32, "Piccolo 2"}},
    {midi_program_ex_id(0x7f, 00, 0x4c), Midi_Program_Ex{Midi_Spec::MT32, "Recorder"}},
    {midi_program_ex_id(0x7f, 00, 0x4d), Midi_Program_Ex{Midi_Spec::MT32, "Pan Pipes"}},
    {midi_program_ex_id(0x7f, 00, 0x4e), Midi_Program_Ex{Midi_Spec::MT32, "Sax 1"}},
    {midi_program_ex_id(0x7f, 00, 0x4f), Midi_Program_Ex{Midi_Spec::MT32, "Sax 2"}},
    {midi_program_ex_id(0x7f, 00, 0x50), Midi_Program_Ex{Midi_Spec::MT32, "Sax 3"}},
    {midi_program_ex_id(0x7f, 00, 0x51), Midi_Program_Ex{Midi_Spec::MT32, "Sax 4"}},
    {midi_program_ex_id(0x7f, 00, 0x52), Midi_Program_Ex{Midi_Spec::MT32, "Clarinet 1"}},
    {midi_program_ex_id(0x7f, 00, 0x53), Midi_Program_Ex{Midi_Spec::MT32, "Clarinet 2"}},
    {midi_program_ex_id(0x7f, 00, 0x54), Midi_Program_Ex{Midi_Spec::MT32, "Oboe"}},
    {midi_program_ex_id(0x7f, 00, 0x55), Midi_Program_Ex{Midi_Spec::MT32, "Engl Horn"}},
    {midi_program_ex_id(0x7f, 00, 0x56), Midi_Program_Ex{Midi_Spec::MT32, "Bassoon"}},
    {midi_program_ex_id(0x7f, 00, 0x57), Midi_Program_Ex{Midi_Spec::MT32, "Harmonica"}},
    {midi_program_ex_id(0x7f, 00, 0x58), Midi_Program_Ex{Midi_Spec::MT32, "Trumpet 1"}},
    {midi_program_ex_id(0x7f, 00, 0x59), Midi_Program_Ex{Midi_Spec::MT32, "Trumpet 2"}},
    {midi_program_ex_id(0x7f, 00, 0x5a), Midi_Program_Ex{Midi_Spec::MT32, "Trombone 1"}},
    {midi_program_ex_id(0x7f, 00, 0x5b), Midi_Program_Ex{Midi_Spec::MT32, "Trombone 2"}},
    {midi_program_ex_id(0x7f, 00, 0x5c), Midi_Program_Ex{Midi_Spec::MT32, "Fr Horn 1"}},
    {midi_program_ex_id(0x7f, 00, 0x5d), Midi_Program_Ex{Midi_Spec::MT32, "Fr Horn 2"}},
    {midi_program_ex_id(0x7f, 00, 0x5e), Midi_Program_Ex{Midi_Spec::MT32, "Tuba"}},
    {midi_program_ex_id(0x7f, 00, 0x5f), Midi_Program_Ex{Midi_Spec::MT32, "Brs Sect 1"}},
    {midi_program_ex_id(0x7f, 00, 0x60), Midi_Program_Ex{Midi_Spec::MT32, "Brs Sect 2"}},
    {midi_program_ex_id(0x7f, 00, 0x61), Midi_Program_Ex{Midi_Spec::MT32, "Vibe 1"}},
    {midi_program_ex_id(0x7f, 00, 0x62), Midi_Program_Ex{Midi_Spec::MT32, "Vibe 2"}},
    {midi_program_ex_id(0x7f, 00, 0x63), Midi_Program_Ex{Midi_Spec::MT32, "Syn Mallet"}},
    {midi_program_ex_id(0x7f, 00, 0x64), Midi_Program_Ex{Midi_Spec::MT32, "Windbell"}},
    {midi_program_ex_id(0x7f, 00, 0x65), Midi_Program_Ex{Midi_Spec::MT32, "Glock"}},
    {midi_program_ex_id(0x7f, 00, 0x66), Midi_Program_Ex{Midi_Spec::MT32, "Tube Bell"}},
    {midi_program_ex_id(0x7f, 00, 0x67), Midi_Program_Ex{Midi_Spec::MT32, "Xylophone"}},
    {midi_program_ex_id(0x7f, 00, 0x68), Midi_Program_Ex{Midi_Spec::MT32, "Marimba"}},
    {midi_program_ex_id(0x7f, 00, 0x69), Midi_Program_Ex{Midi_Spec::MT32, "Koto"}},
    {midi_program_ex_id(0x7f, 00, 0x6a), Midi_Program_Ex{Midi_Spec::MT32, "Sho"}},
    {midi_program_ex_id(0x7f, 00, 0x6b), Midi_Program_Ex{Midi_Spec::MT32, "Shakuhachi"}},
    {midi_program_ex_id(0x7f, 00, 0x6c), Midi_Program_Ex{Midi_Spec::MT32, "Whistle 1"}},
    {midi_program_ex_id(0x7f, 00, 0x6d), Midi_Program_Ex{Midi_Spec::MT32, "Whistle 2"}},
    {midi_program_ex_id(0x7f, 00, 0x6e), Midi_Program_Ex{Midi_Spec::MT32, "Bottleblow"}},
    {midi_program_ex_id(0x7f, 00, 0x6f), Midi_Program_Ex{Midi_Spec::MT32, "Breathpipe"}},
    {midi_program_ex_id(0x7f, 00, 0x70), Midi_Program_Ex{Midi_Spec::MT32, "Timpani"}},
    {midi_program_ex_id(0x7f, 00, 0x71), Midi_Program_Ex{Midi_Spec::MT32, "Melodic Tom"}},
    {midi_program_ex_id(0x7f, 00, 0x72), Midi_Program_Ex{Midi_Spec::MT32, "Deep Snare"}},
    {midi_program_ex_id(0x7f, 00, 0x73), Midi_Program_Ex{Midi_Spec::MT32, "Elec Perc 1"}},
    {midi_program_ex_id(0x7f, 00, 0x74), Midi_Program_Ex{Midi_Spec::MT32, "Elec Perc 2"}},
    {midi_program_ex_id(0x7f, 00, 0x75), Midi_Program_Ex{Midi_Spec::MT32, "Taiko"}},
    {midi_program_ex_id(0x7f, 00, 0x76), Midi_Program_Ex{Midi_Spec::MT32, "Taiko Rim"}},
    {midi_program_ex_id(0x7f, 00, 0x77), Midi_Program_Ex{Midi_Spec::MT32, "Cymbal"}},
    {midi_program_ex_id(0x7f, 00, 0x78), Midi_Program_Ex{Midi_Spec::MT32, "Castanets"}},
    {midi_program_ex_id(0x7f, 00, 0x79), Midi_Program_Ex{Midi_Spec::MT32, "Triangle"}},
    {midi_program_ex_id(0x7f, 00, 0x7a), Midi_Program_Ex{Midi_Spec::MT32, "Orche Hit"}},
    {midi_program_ex_id(0x7f, 00, 0x7b), Midi_Program_Ex{Midi_Spec::MT32, "Telephone"}},
    {midi_program_ex_id(0x7f, 00, 0x7c), Midi_Program_Ex{Midi_Spec::MT32, "Bird Tweet"}},
    {midi_program_ex_id(0x7f, 00, 0x7d), Midi_Program_Ex{Midi_Spec::MT32, "One Note Jam"}},
    {midi_program_ex_id(0x7f, 00, 0x7e), Midi_Program_Ex{Midi_Spec::MT32, "Water Bell"}},
    {midi_program_ex_id(0x7f, 00, 0x7f), Midi_Program_Ex{Midi_Spec::MT32, "Jungle Tune"}},
    {midi_program_ex_id(00, 0x1, 00), Midi_Program_Ex{Midi_Spec::XG, "Grand PianoK"}},
    {midi_program_ex_id(00, 0x1, 0x1), Midi_Program_Ex{Midi_Spec::XG, "Bright Piano K"}},
    {midi_program_ex_id(00, 0x1, 0x2), Midi_Program_Ex{Midi_Spec::XG, "Electric Grand Piano K"}},
    {midi_program_ex_id(00, 0x1, 0x3), Midi_Program_Ex{Midi_Spec::XG, "Honky Tonk K"}},
    {midi_program_ex_id(00, 0x1, 0x4), Midi_Program_Ex{Midi_Spec::XG, "Electric Piano 1K"}},
    {midi_program_ex_id(00, 0x1, 0x5), Midi_Program_Ex{Midi_Spec::XG, "Electric Piano2 K"}},
    {midi_program_ex_id(00, 0x1, 0x6), Midi_Program_Ex{Midi_Spec::XG, "Harpsichord K"}},
    {midi_program_ex_id(00, 0x1, 0x7), Midi_Program_Ex{Midi_Spec::XG, "Clavinet K"}},
    {midi_program_ex_id(00, 0x1, 0xb), Midi_Program_Ex{Midi_Spec::XG, "VibesK"}},
    {midi_program_ex_id(00, 0x1, 0xc), Midi_Program_Ex{Midi_Spec::XG, "Marimba K"}},
    {midi_program_ex_id(00, 0x3, 0x30), Midi_Program_Ex{Midi_Spec::XG, "S.Strngs"}},
    {midi_program_ex_id(00, 0x3, 0x31), Midi_Program_Ex{Midi_Spec::XG, "S.SlwStr"}},
    {midi_program_ex_id(00, 0x3, 0x34), Midi_Program_Ex{Midi_Spec::XG, "S.Choir"}},
    {midi_program_ex_id(00, 0x6, 0x27), Midi_Program_Ex{Midi_Spec::XG, "MelloSB1"}},
    {midi_program_ex_id(00, 0x6, 0x3c), Midi_Program_Ex{Midi_Spec::XG, "FrHrSolo"}},
    {midi_program_ex_id(00, 0x6, 0x50), Midi_Program_Ex{Midi_Spec::XG, "Square 2"}},
    {midi_program_ex_id(00, 0x6, 0x51), Midi_Program_Ex{Midi_Spec::XG, "Saw 2"}},
    {midi_program_ex_id(00, 0x8, 0x28), Midi_Program_Ex{Midi_Spec::XG, "SlowVln"}},
    {midi_program_ex_id(00, 0x8, 0x2c), Midi_Program_Ex{Midi_Spec::XG, "SlowTrStr"}},
    {midi_program_ex_id(00, 0x8, 0x30), Midi_Program_Ex{Midi_Spec::XG, "SlowStr"}},
    {midi_program_ex_id(00, 0x8, 0x31), Midi_Program_Ex{Midi_Spec::XG, "LegatoSt"}},
    {midi_program_ex_id(00, 0x8, 0x50), Midi_Program_Ex{Midi_Spec::XG, "LMSquare"}},
    {midi_program_ex_id(00, 0x8, 0x51), Midi_Program_Ex{Midi_Spec::XG, "ThickSaw"}},
    {midi_program_ex_id(00, 0x8, 0x66), Midi_Program_Ex{Midi_Spec::XG, "EchoPad2"}},
    {midi_program_ex_id(00, 0xc, 0x27), Midi_Program_Ex{Midi_Spec::XG, "Seq Bass"}},
    {midi_program_ex_id(00, 0xc, 0x3e), Midi_Program_Ex{Midi_Spec::XG, "QuackBr"}},
    {midi_program_ex_id(00, 0xc, 0x62), Midi_Program_Ex{Midi_Spec::XG, "SynDrCmp"}},
    {midi_program_ex_id(00, 0xe, 0x62), Midi_Program_Ex{Midi_Spec::XG, "Popcorn"}},
    {midi_program_ex_id(00, 0xe, 0x66), Midi_Program_Ex{Midi_Spec::XG, "Echo Pan"}},
    {midi_program_ex_id(00, 0x10, 0x18), Midi_Program_Ex{Midi_Spec::XG, "NylonGt2"}},
    {midi_program_ex_id(00, 0x10, 0x19), Midi_Program_Ex{Midi_Spec::XG, "SteelGt2"}},
    {midi_program_ex_id(00, 0x10, 0x34), Midi_Program_Ex{Midi_Spec::XG, "Ch.Aahs2"}},
    {midi_program_ex_id(00, 0x10, 0x38), Midi_Program_Ex{Midi_Spec::XG, "Trumpet2"}},
    {midi_program_ex_id(00, 0x10, 0x3a), Midi_Program_Ex{Midi_Spec::XG, "Tuba 2"}},
    {midi_program_ex_id(00, 0x10, 0x57), Midi_Program_Ex{Midi_Spec::XG, "Big&Low"}},
    {midi_program_ex_id(00, 0x10, 0x59), Midi_Program_Ex{Midi_Spec::XG, "ThickPad"}},
    {midi_program_ex_id(00, 0x11, 0x38), Midi_Program_Ex{Midi_Spec::XG, "BriteTrp"}},
    {midi_program_ex_id(00, 0x11, 0x59), Midi_Program_Ex{Midi_Spec::XG, "Soft Pad"}},
    {midi_program_ex_id(00, 0x12, 00), Midi_Program_Ex{Midi_Spec::XG, "MelloGrP"}},
    {midi_program_ex_id(00, 0x12, 0x4), Midi_Program_Ex{Midi_Spec::XG, "MelloEP1"}},
    {midi_program_ex_id(00, 0x12, 0x1a), Midi_Program_Ex{Midi_Spec::XG, "MelloGtr"}},
    {midi_program_ex_id(00, 0x12, 0x21), Midi_Program_Ex{Midi_Spec::XG, "FingrDrk"}},
    {midi_program_ex_id(00, 0x12, 0x26), Midi_Program_Ex{Midi_Spec::XG, "SynBa1Dk"}},
    {midi_program_ex_id(00, 0x12, 0x27), Midi_Program_Ex{Midi_Spec::XG, "SynBa1Dk"}},
    {midi_program_ex_id(00, 0x12, 0x28), Midi_Program_Ex{Midi_Spec::XG, "ClkSynBa"}},
    {midi_program_ex_id(00, 0x12, 0x39), Midi_Program_Ex{Midi_Spec::XG, "Trmbone2"}},
    {midi_program_ex_id(00, 0x12, 0x3f), Midi_Program_Ex{Midi_Spec::XG, "Soft Brs"}},
    {midi_program_ex_id(00, 0x12, 0x50), Midi_Program_Ex{Midi_Spec::XG, "Hollow"}},
    {midi_program_ex_id(00, 0x12, 0x51), Midi_Program_Ex{Midi_Spec::XG, "DynaSaw"}},
    {midi_program_ex_id(00, 0x12, 0x59), Midi_Program_Ex{Midi_Spec::XG, "SinePad"}},
    {midi_program_ex_id(00, 0x12, 0x62), Midi_Program_Ex{Midi_Spec::XG, "TinyBell"}},
    {midi_program_ex_id(00, 0x12, 0x63), Midi_Program_Ex{Midi_Spec::XG, "WarmAtms"}},
    {midi_program_ex_id(00, 0x13, 0x27), Midi_Program_Ex{Midi_Spec::XG, "SynBa2Dk"}},
    {midi_program_ex_id(00, 0x13, 0x50), Midi_Program_Ex{Midi_Spec::XG, "Shmoog"}},
    {midi_program_ex_id(00, 0x13, 0x51), Midi_Program_Ex{Midi_Spec::XG, "DigiSaw"}},
    {midi_program_ex_id(00, 0x13, 0x63), Midi_Program_Ex{Midi_Spec::XG, "HollwRls"}},
    {midi_program_ex_id(00, 0x14, 0x26), Midi_Program_Ex{Midi_Spec::XG, "FastResB"}},
    {midi_program_ex_id(00, 0x14, 0x3e), Midi_Program_Ex{Midi_Spec::XG, "RezSynBr"}},
    {midi_program_ex_id(00, 0x14, 0x51), Midi_Program_Ex{Midi_Spec::XG, "Big Lead"}},
    {midi_program_ex_id(00, 0x14, 0x5f), Midi_Program_Ex{Midi_Spec::XG, "Shwimmer"}},
    {midi_program_ex_id(00, 0x18, 0x11), Midi_Program_Ex{Midi_Spec::XG, "70sPcOr1"}},
    {midi_program_ex_id(00, 0x18, 0x26), Midi_Program_Ex{Midi_Spec::XG, "AcidBass"}},
    {midi_program_ex_id(00, 0x18, 0x30), Midi_Program_Ex{Midi_Spec::XG, "ArcoStr"}},
    {midi_program_ex_id(00, 0x18, 0x3e), Midi_Program_Ex{Midi_Spec::XG, "PolyBrss"}},
    {midi_program_ex_id(00, 0x18, 0x51), Midi_Program_Ex{Midi_Spec::XG, "HeavySyn"}},
    {midi_program_ex_id(00, 0x18, 0x55), Midi_Program_Ex{Midi_Spec::XG, "SynthAah"}},
    {midi_program_ex_id(00, 0x19, 0x6), Midi_Program_Ex{Midi_Spec::XG, "Harpsi.2"}},
    {midi_program_ex_id(00, 0x19, 0x18), Midi_Program_Ex{Midi_Spec::XG, "NylonGt3"}},
    {midi_program_ex_id(00, 0x19, 0x51), Midi_Program_Ex{Midi_Spec::XG, "WaspySyn"}},
    {midi_program_ex_id(00, 0x1b, 0x7), Midi_Program_Ex{Midi_Spec::XG, "ClaviWah"}},
    {midi_program_ex_id(00, 0x1b, 0x21), Midi_Program_Ex{Midi_Spec::XG, "FlangeBa"}},
    {midi_program_ex_id(00, 0x1b, 0x24), Midi_Program_Ex{Midi_Spec::XG, "ResoSlap"}},
    {midi_program_ex_id(00, 0x1b, 0x32), Midi_Program_Ex{Midi_Spec::XG, "ResoStr"}},
    {midi_program_ex_id(00, 0x1b, 0x3e), Midi_Program_Ex{Midi_Spec::XG, "SynBras3"}},
    {midi_program_ex_id(00, 0x1b, 0x5f), Midi_Program_Ex{Midi_Spec::XG, "Converge"}},
    {midi_program_ex_id(00, 0x1b, 0x61), Midi_Program_Ex{Midi_Spec::XG, "Prologue"}},
    {midi_program_ex_id(00, 0x1c, 0x22), Midi_Program_Ex{Midi_Spec::XG, "MutePkBa"}},
    {midi_program_ex_id(00, 0x1c, 0x69), Midi_Program_Ex{Midi_Spec::XG, "MuteBnjo"}},
    {midi_program_ex_id(00, 0x20, 0x2), Midi_Program_Ex{Midi_Spec::XG, "Det.CP80"}},
    {midi_program_ex_id(00, 0x20, 0x4), Midi_Program_Ex{Midi_Spec::XG, "Chor.EP1"}},
    {midi_program_ex_id(00, 0x20, 0x5), Midi_Program_Ex{Midi_Spec::XG, "Chor.EP2"}},
    {midi_program_ex_id(00, 0x20, 0x10), Midi_Program_Ex{Midi_Spec::XG, "DetDrwOr"}},
    {midi_program_ex_id(00, 0x20, 0x11), Midi_Program_Ex{Midi_Spec::XG, "DetPrcOr"}},
    {midi_program_ex_id(00, 0x20, 0x13), Midi_Program_Ex{Midi_Spec::XG, "ChurOrg3"}},
    {midi_program_ex_id(00, 0x20, 0x15), Midi_Program_Ex{Midi_Spec::XG, "AccordIt"}},
    {midi_program_ex_id(00, 0x20, 0x16), Midi_Program_Ex{Midi_Spec::XG, "Harmo 2"}},
    {midi_program_ex_id(00, 0x20, 0x1a), Midi_Program_Ex{Midi_Spec::XG, "JazzAmp"}},
    {midi_program_ex_id(00, 0x20, 0x1b), Midi_Program_Ex{Midi_Spec::XG, "ChorusGt"}},
    {midi_program_ex_id(00, 0x20, 0x23), Midi_Program_Ex{Midi_Spec::XG, "Fretles2"}},
    {midi_program_ex_id(00, 0x20, 0x24), Midi_Program_Ex{Midi_Spec::XG, "PunchThm"}},
    {midi_program_ex_id(00, 0x20, 0x27), Midi_Program_Ex{Midi_Spec::XG, "SmthBa 2"}},
    {midi_program_ex_id(00, 0x20, 0x34), Midi_Program_Ex{Midi_Spec::XG, "MelChoir"}},
    {midi_program_ex_id(00, 0x20, 0x38), Midi_Program_Ex{Midi_Spec::XG, "WarmTrp"}},
    {midi_program_ex_id(00, 0x20, 0x3c), Midi_Program_Ex{Midi_Spec::XG, "FrHorn2"}},
    {midi_program_ex_id(00, 0x20, 0x3e), Midi_Program_Ex{Midi_Spec::XG, "JumpBrss"}},
    {midi_program_ex_id(00, 0x20, 0x68), Midi_Program_Ex{Midi_Spec::XG, "DetSitar"}},
    {midi_program_ex_id(00, 0x21, 0x5), Midi_Program_Ex{Midi_Spec::XG, "DX Hard"}},
    {midi_program_ex_id(00, 0x21, 0x10), Midi_Program_Ex{Midi_Spec::XG, "60sDrOr1"}},
    {midi_program_ex_id(00, 0x21, 0x11), Midi_Program_Ex{Midi_Spec::XG, "LiteOrg"}},
    {midi_program_ex_id(00, 0x21, 0x23), Midi_Program_Ex{Midi_Spec::XG, "Fretles3"}},
    {midi_program_ex_id(00, 0x22, 0x5), Midi_Program_Ex{Midi_Spec::XG, "DXLegend"}},
    {midi_program_ex_id(00, 0x22, 0x10), Midi_Program_Ex{Midi_Spec::XG, "60sDrOr2"}},
    {midi_program_ex_id(00, 0x22, 0x23), Midi_Program_Ex{Midi_Spec::XG, "Fretles4"}},
    {midi_program_ex_id(00, 0x23, 0x6), Midi_Program_Ex{Midi_Spec::XG, "Harpsi.3"}},
    {midi_program_ex_id(00, 0x23, 0xf), Midi_Program_Ex{Midi_Spec::XG, "Dulcimr2"}},
    {midi_program_ex_id(00, 0x23, 0x10), Midi_Program_Ex{Midi_Spec::XG, "70sDrOr1"}},
    {midi_program_ex_id(00, 0x23, 0x13), Midi_Program_Ex{Midi_Spec::XG, "ChurOrg2"}},
    {midi_program_ex_id(00, 0x23, 0x19), Midi_Program_Ex{Midi_Spec::XG, "12StrGtr"}},
    {midi_program_ex_id(00, 0x23, 0x26), Midi_Program_Ex{Midi_Spec::XG, "Clv Bass"}},
    {midi_program_ex_id(00, 0x23, 0x30), Midi_Program_Ex{Midi_Spec::XG, "60sStrng"}},
    {midi_program_ex_id(00, 0x23, 0x37), Midi_Program_Ex{Midi_Spec::XG, "OrchHit2"}},
    {midi_program_ex_id(00, 0x23, 0x3d), Midi_Program_Ex{Midi_Spec::XG, "Tp&TbSec"}},
    {midi_program_ex_id(00, 0x23, 0x56), Midi_Program_Ex{Midi_Spec::XG, "Big Five"}},
    {midi_program_ex_id(00, 0x23, 0x62), Midi_Program_Ex{Midi_Spec::XG, "RndGlock"}},
    {midi_program_ex_id(00, 0x23, 0x68), Midi_Program_Ex{Midi_Spec::XG, "Sitar 2"}},
    {midi_program_ex_id(00, 0x24, 0x10), Midi_Program_Ex{Midi_Spec::XG, "DrawOrg2"}},
    {midi_program_ex_id(00, 0x25, 0x10), Midi_Program_Ex{Midi_Spec::XG, "60sDrOr3"}},
    {midi_program_ex_id(00, 0x25, 0x11), Midi_Program_Ex{Midi_Spec::XG, "PercOrg2"}},
    {midi_program_ex_id(00, 0x25, 0x3c), Midi_Program_Ex{Midi_Spec::XG, "HornOrch"}},
    {midi_program_ex_id(00, 0x26, 0x10), Midi_Program_Ex{Midi_Spec::XG, "EvenBar"}},
    {midi_program_ex_id(00, 0x28, 00), Midi_Program_Ex{Midi_Spec::XG, "PianoStr"}},
    {midi_program_ex_id(00, 0x28, 0x2), Midi_Program_Ex{Midi_Spec::XG, "ElGrPno1"}},
    {midi_program_ex_id(00, 0x28, 0x4), Midi_Program_Ex{Midi_Spec::XG, "HardEl.P"}},
    {midi_program_ex_id(00, 0x28, 0x5), Midi_Program_Ex{Midi_Spec::XG, "DX Phase"}},
    {midi_program_ex_id(00, 0x28, 0x10), Midi_Program_Ex{Midi_Spec::XG, "16+2\"2/3"}},
    {midi_program_ex_id(00, 0x28, 0x13), Midi_Program_Ex{Midi_Spec::XG, "NotreDam"}},
    {midi_program_ex_id(00, 0x28, 0x14), Midi_Program_Ex{Midi_Spec::XG, "Puff Org"}},
    {midi_program_ex_id(00, 0x28, 0x19), Midi_Program_Ex{Midi_Spec::XG, "Nyln&Stl"}},
    {midi_program_ex_id(00, 0x28, 0x1c), Midi_Program_Ex{Midi_Spec::XG, "FunkGtr1"}},
    {midi_program_ex_id(00, 0x28, 0x1e), Midi_Program_Ex{Midi_Spec::XG, "FeedbkGt"}},
    {midi_program_ex_id(00, 0x28, 0x20), Midi_Program_Ex{Midi_Spec::XG, "Jazz Rhythm"}},
    {midi_program_ex_id(00, 0x28, 0x21), Midi_Program_Ex{Midi_Spec::XG, "Ba&DstEG"}},
    {midi_program_ex_id(00, 0x28, 0x26), Midi_Program_Ex{Midi_Spec::XG, "Techno Bass"}},
    {midi_program_ex_id(00, 0x28, 0x27), Midi_Program_Ex{Midi_Spec::XG, "Modular Bass"}},
    {midi_program_ex_id(00, 0x28, 0x2c), Midi_Program_Ex{Midi_Spec::XG, "Susp Str"}},
    {midi_program_ex_id(00, 0x28, 0x2e), Midi_Program_Ex{Midi_Spec::XG, "Yang Chin"}},
    {midi_program_ex_id(00, 0x28, 0x30), Midi_Program_Ex{Midi_Spec::XG, "Orchestra"}},
    {midi_program_ex_id(00, 0x28, 0x31), Midi_Program_Ex{Midi_Spec::XG, "Warm Str"}},
    {midi_program_ex_id(00, 0x28, 0x34), Midi_Program_Ex{Midi_Spec::XG, "ChoirStr"}},
    {midi_program_ex_id(00, 0x28, 0x36), Midi_Program_Ex{Midi_Spec::XG, "SynVox2"}},
    {midi_program_ex_id(00, 0x28, 0x3d), Midi_Program_Ex{Midi_Spec::XG, "BrassSec2"}},
    {midi_program_ex_id(00, 0x28, 0x3f), Midi_Program_Ex{Midi_Spec::XG, "SynBras4"}},
    {midi_program_ex_id(00, 0x28, 0x41), Midi_Program_Ex{Midi_Spec::XG, "Sax Sect"}},
    {midi_program_ex_id(00, 0x28, 0x42), Midi_Program_Ex{Midi_Spec::XG, "BrthTnSx"}},
    {midi_program_ex_id(00, 0x28, 0x51), Midi_Program_Ex{Midi_Spec::XG, "Pulse Saw"}},
    {midi_program_ex_id(00, 0x28, 0x62), Midi_Program_Ex{Midi_Spec::XG, "GlockChi"}},
    {midi_program_ex_id(00, 0x28, 0x63), Midi_Program_Ex{Midi_Spec::XG, "NylonEP"}},
    {midi_program_ex_id(00, 0x29, 00), Midi_Program_Ex{Midi_Spec::XG, "Dream"}},
    {midi_program_ex_id(00, 0x29, 0x2), Midi_Program_Ex{Midi_Spec::XG, "ElGrPno2"}},
    {midi_program_ex_id(00, 0x29, 0x5), Midi_Program_Ex{Midi_Spec::XG, "DX+Analg"}},
    {midi_program_ex_id(00, 0x29, 0x19), Midi_Program_Ex{Midi_Spec::XG, "Stl&Body"}},
    {midi_program_ex_id(00, 0x29, 0x1c), Midi_Program_Ex{Midi_Spec::XG, "MuteStlG"}},
    {midi_program_ex_id(00, 0x29, 0x1e), Midi_Program_Ex{Midi_Spec::XG, "FeedbGt2"}},
    {midi_program_ex_id(00, 0x29, 0x27), Midi_Program_Ex{Midi_Spec::XG, "DX Bass"}},
    {midi_program_ex_id(00, 0x29, 0x30), Midi_Program_Ex{Midi_Spec::XG, "Orchstr2"}},
    {midi_program_ex_id(00, 0x29, 0x31), Midi_Program_Ex{Midi_Spec::XG, "Kingdom"}},
    {midi_program_ex_id(00, 0x29, 0x36), Midi_Program_Ex{Midi_Spec::XG, "Choral"}},
    {midi_program_ex_id(00, 0x29, 0x3d), Midi_Program_Ex{Midi_Spec::XG, "HiBrass"}},
    {midi_program_ex_id(00, 0x29, 0x3f), Midi_Program_Ex{Midi_Spec::XG, "ChorBrss"}},
    {midi_program_ex_id(00, 0x29, 0x42), Midi_Program_Ex{Midi_Spec::XG, "SoftTenr"}},
    {midi_program_ex_id(00, 0x29, 0x51), Midi_Program_Ex{Midi_Spec::XG, "Dr. Lead"}},
    {midi_program_ex_id(00, 0x29, 0x62), Midi_Program_Ex{Midi_Spec::XG, "ClearBel"}},
    {midi_program_ex_id(00, 0x2a, 0x5), Midi_Program_Ex{Midi_Spec::XG, "DXKotoEP"}},
    {midi_program_ex_id(00, 0x2a, 0x30), Midi_Program_Ex{Midi_Spec::XG, "TremOrch"}},
    {midi_program_ex_id(00, 0x2a, 0x3d), Midi_Program_Ex{Midi_Spec::XG, "MelloBrs"}},
    {midi_program_ex_id(00, 0x2a, 0x62), Midi_Program_Ex{Midi_Spec::XG, "ChorBell"}},
    {midi_program_ex_id(00, 0x2b, 0x18), Midi_Program_Ex{Midi_Spec::XG, "VelGtHrm"}},
    {midi_program_ex_id(00, 0x2b, 0x1c), Midi_Program_Ex{Midi_Spec::XG, "FunkGtr2"}},
    {midi_program_ex_id(00, 0x2b, 0x1d), Midi_Program_Ex{Midi_Spec::XG, "Gt.Pinch"}},
    {midi_program_ex_id(00, 0x2b, 0x21), Midi_Program_Ex{Midi_Spec::XG, "FngrSlap"}},
    {midi_program_ex_id(00, 0x2b, 0x25), Midi_Program_Ex{Midi_Spec::XG, "VeloSlap"}},
    {midi_program_ex_id(00, 0x2b, 0x41), Midi_Program_Ex{Midi_Spec::XG, "HyprAlto"}},
    {midi_program_ex_id(00, 0x2d, 0x4), Midi_Program_Ex{Midi_Spec::XG, "VX El.P1"}},
    {midi_program_ex_id(00, 0x2d, 0x5), Midi_Program_Ex{Midi_Spec::XG, "VX El.P2"}},
    {midi_program_ex_id(00, 0x2d, 0xb), Midi_Program_Ex{Midi_Spec::XG, "HardVibe"}},
    {midi_program_ex_id(00, 0x2d, 0x1c), Midi_Program_Ex{Midi_Spec::XG, "Jazz Man"}},
    {midi_program_ex_id(00, 0x2d, 0x20), Midi_Program_Ex{Midi_Spec::XG, "VX Upright"}},
    {midi_program_ex_id(00, 0x2d, 0x21), Midi_Program_Ex{Midi_Spec::XG, "FngBass2"}},
    {midi_program_ex_id(00, 0x2d, 0x30), Midi_Program_Ex{Midi_Spec::XG, "VeloStr"}},
    {midi_program_ex_id(00, 0x2d, 0x3e), Midi_Program_Ex{Midi_Spec::XG, "AnaVelBr"}},
    {midi_program_ex_id(00, 0x2d, 0x3f), Midi_Program_Ex{Midi_Spec::XG, "VelBras2"}},
    {midi_program_ex_id(00, 0x2d, 0x51), Midi_Program_Ex{Midi_Spec::XG, "VeloLead"}},
    {midi_program_ex_id(00, 0x2d, 0x60), Midi_Program_Ex{Midi_Spec::XG, "ClaviPad"}},
    {midi_program_ex_id(00, 0x40, 0x4), Midi_Program_Ex{Midi_Spec::XG, "60sEl.P"}},
    {midi_program_ex_id(00, 0x40, 0x7), Midi_Program_Ex{Midi_Spec::XG, "PulseClv"}},
    {midi_program_ex_id(00, 0x40, 0xa), Midi_Program_Ex{Midi_Spec::XG, "Orgel"}},
    {midi_program_ex_id(00, 0x40, 0xc), Midi_Program_Ex{Midi_Spec::XG, "SineMrmb"}},
    {midi_program_ex_id(00, 0x40, 0x10), Midi_Program_Ex{Midi_Spec::XG, "Organ Ba"}},
    {midi_program_ex_id(00, 0x40, 0x12), Midi_Program_Ex{Midi_Spec::XG, "RotaryOr"}},
    {midi_program_ex_id(00, 0x40, 0x13), Midi_Program_Ex{Midi_Spec::XG, "OrgFlute"}},
    {midi_program_ex_id(00, 0x40, 0x17), Midi_Program_Ex{Midi_Spec::XG, "TngoAcd2"}},
    {midi_program_ex_id(00, 0x40, 0x26), Midi_Program_Ex{Midi_Spec::XG, "Oscar"}},
    {midi_program_ex_id(00, 0x40, 0x27), Midi_Program_Ex{Midi_Spec::XG, "X WireBa"}},
    {midi_program_ex_id(00, 0x40, 0x31), Midi_Program_Ex{Midi_Spec::XG, "70s Str"}},
    {midi_program_ex_id(00, 0x40, 0x32), Midi_Program_Ex{Midi_Spec::XG, "Syn Str4"}},
    {midi_program_ex_id(00, 0x40, 0x36), Midi_Program_Ex{Midi_Spec::XG, "AnaVoice"}},
    {midi_program_ex_id(00, 0x40, 0x37), Midi_Program_Ex{Midi_Spec::XG, "Impact"}},
    {midi_program_ex_id(00, 0x40, 0x3e), Midi_Program_Ex{Midi_Spec::XG, "AnaBrss1"}},
    {midi_program_ex_id(00, 0x40, 0x3f), Midi_Program_Ex{Midi_Spec::XG, "AnaBras2"}},
    {midi_program_ex_id(00, 0x40, 0x42), Midi_Program_Ex{Midi_Spec::XG, "TnrSax 2"}},
    {midi_program_ex_id(00, 0x40, 0x50), Midi_Program_Ex{Midi_Spec::XG, "Mellow"}},
    {midi_program_ex_id(00, 0x40, 0x53), Midi_Program_Ex{Midi_Spec::XG, "Rubby"}},
    {midi_program_ex_id(00, 0x40, 0x54), Midi_Program_Ex{Midi_Spec::XG, "DistLead"}},
    {midi_program_ex_id(00, 0x40, 0x55), Midi_Program_Ex{Midi_Spec::XG, "VoxLead"}},
    {midi_program_ex_id(00, 0x40, 0x57), Midi_Program_Ex{Midi_Spec::XG, "Fat&Prky"}},
    {midi_program_ex_id(00, 0x40, 0x58), Midi_Program_Ex{Midi_Spec::XG, "Fantasy2"}},
    {midi_program_ex_id(00, 0x40, 0x59), Midi_Program_Ex{Midi_Spec::XG, "Horn Pad"}},
    {midi_program_ex_id(00, 0x40, 0x5a), Midi_Program_Ex{Midi_Spec::XG, "PolyPd80"}},
    {midi_program_ex_id(00, 0x40, 0x5b), Midi_Program_Ex{Midi_Spec::XG, "Heaven2"}},
    {midi_program_ex_id(00, 0x40, 0x5c), Midi_Program_Ex{Midi_Spec::XG, "Glacier"}},
    {midi_program_ex_id(00, 0x40, 0x5d), Midi_Program_Ex{Midi_Spec::XG, "Tine Pad"}},
    {midi_program_ex_id(00, 0x40, 0x5f), Midi_Program_Ex{Midi_Spec::XG, "PolarPad"}},
    {midi_program_ex_id(00, 0x40, 0x60), Midi_Program_Ex{Midi_Spec::XG, "HrmoRain"}},
    {midi_program_ex_id(00, 0x40, 0x61), Midi_Program_Ex{Midi_Spec::XG, "Ancestrl"}},
    {midi_program_ex_id(00, 0x40, 0x62), Midi_Program_Ex{Midi_Spec::XG, "SynMalet"}},
    {midi_program_ex_id(00, 0x40, 0x63), Midi_Program_Ex{Midi_Spec::XG, "NylnHarp"}},
    {midi_program_ex_id(00, 0x40, 0x64), Midi_Program_Ex{Midi_Spec::XG, "FantaBel"}},
    {midi_program_ex_id(00, 0x40, 0x65), Midi_Program_Ex{Midi_Spec::XG, "GobSyn"}},
    {midi_program_ex_id(00, 0x40, 0x66), Midi_Program_Ex{Midi_Spec::XG, "EchoBell"}},
    {midi_program_ex_id(00, 0x40, 0x67), Midi_Program_Ex{Midi_Spec::XG, "Starz"}},
    {midi_program_ex_id(00, 0x40, 0x6f), Midi_Program_Ex{Midi_Spec::XG, "Shanai2"}},
    {midi_program_ex_id(00, 0x40, 0x75), Midi_Program_Ex{Midi_Spec::XG, "Mel Tom2"}},
    {midi_program_ex_id(00, 0x40, 0x76), Midi_Program_Ex{Midi_Spec::XG, "Ana Tom"}},
    {midi_program_ex_id(00, 0x41, 0x7), Midi_Program_Ex{Midi_Spec::XG, "PierceCl"}},
    {midi_program_ex_id(00, 0x41, 0x10), Midi_Program_Ex{Midi_Spec::XG, "70sDrOr2"}},
    {midi_program_ex_id(00, 0x41, 0x12), Midi_Program_Ex{Midi_Spec::XG, "SlwRotar"}},
    {midi_program_ex_id(00, 0x41, 0x13), Midi_Program_Ex{Midi_Spec::XG, "TrmOrgFl"}},
    {midi_program_ex_id(00, 0x41, 0x1f), Midi_Program_Ex{Midi_Spec::XG, "GtFeedbk"}},
    {midi_program_ex_id(00, 0x41, 0x21), Midi_Program_Ex{Midi_Spec::XG, "ModAlem"}},
    {midi_program_ex_id(00, 0x41, 0x26), Midi_Program_Ex{Midi_Spec::XG, "SqrBass"}},
    {midi_program_ex_id(00, 0x41, 0x32), Midi_Program_Ex{Midi_Spec::XG, "SS Str"}},
    {midi_program_ex_id(00, 0x41, 0x50), Midi_Program_Ex{Midi_Spec::XG, "SoloSine"}},
    {midi_program_ex_id(00, 0x41, 0x52), Midi_Program_Ex{Midi_Spec::XG, "Pure Pad"}},
    {midi_program_ex_id(00, 0x41, 0x54), Midi_Program_Ex{Midi_Spec::XG, "WireLead"}},
    {midi_program_ex_id(00, 0x41, 0x57), Midi_Program_Ex{Midi_Spec::XG, "SoftWurl"}},
    {midi_program_ex_id(00, 0x41, 0x59), Midi_Program_Ex{Midi_Spec::XG, "RotarStr"}},
    {midi_program_ex_id(00, 0x41, 0x5a), Midi_Program_Ex{Midi_Spec::XG, "ClickPad"}},
    {midi_program_ex_id(00, 0x41, 0x5c), Midi_Program_Ex{Midi_Spec::XG, "GlassPad"}},
    {midi_program_ex_id(00, 0x41, 0x5d), Midi_Program_Ex{Midi_Spec::XG, "Pan Pad"}},
    {midi_program_ex_id(00, 0x41, 0x60), Midi_Program_Ex{Midi_Spec::XG, "AfrcnWod"}},
    {midi_program_ex_id(00, 0x41, 0x62), Midi_Program_Ex{Midi_Spec::XG, "SftCryst"}},
    {midi_program_ex_id(00, 0x41, 0x63), Midi_Program_Ex{Midi_Spec::XG, "Harp Vox"}},
    {midi_program_ex_id(00, 0x41, 0x65), Midi_Program_Ex{Midi_Spec::XG, "50sSciFi"}},
    {midi_program_ex_id(00, 0x41, 0x66), Midi_Program_Ex{Midi_Spec::XG, "Big Pan"}},
    {midi_program_ex_id(00, 0x41, 0x75), Midi_Program_Ex{Midi_Spec::XG, "Real Tom"}},
    {midi_program_ex_id(00, 0x41, 0x76), Midi_Program_Ex{Midi_Spec::XG, "ElecPerc"}},
    {midi_program_ex_id(00, 0x42, 0x10), Midi_Program_Ex{Midi_Spec::XG, "CheezOrg"}},
    {midi_program_ex_id(00, 0x42, 0x12), Midi_Program_Ex{Midi_Spec::XG, "FstRotar"}},
    {midi_program_ex_id(00, 0x42, 0x1f), Midi_Program_Ex{Midi_Spec::XG, "GtrHrmo2"}},
    {midi_program_ex_id(00, 0x42, 0x26), Midi_Program_Ex{Midi_Spec::XG, "RubberBa"}},
    {midi_program_ex_id(00, 0x42, 0x50), Midi_Program_Ex{Midi_Spec::XG, "SineLead"}},
    {midi_program_ex_id(00, 0x42, 0x5a), Midi_Program_Ex{Midi_Spec::XG, "Ana Pad"}},
    {midi_program_ex_id(00, 0x42, 0x5b), Midi_Program_Ex{Midi_Spec::XG, "Itopia"}},
    {midi_program_ex_id(00, 0x42, 0x5f), Midi_Program_Ex{Midi_Spec::XG, "Celstial"}},
    {midi_program_ex_id(00, 0x42, 0x60), Midi_Program_Ex{Midi_Spec::XG, "Caribean"}},
    {midi_program_ex_id(00, 0x42, 0x62), Midi_Program_Ex{Midi_Spec::XG, "LoudGlok"}},
    {midi_program_ex_id(00, 0x42, 0x63), Midi_Program_Ex{Midi_Spec::XG, "AtmosPad"}},
    {midi_program_ex_id(00, 0x42, 0x65), Midi_Program_Ex{Midi_Spec::XG, "Ring Pad"}},
    {midi_program_ex_id(00, 0x42, 0x66), Midi_Program_Ex{Midi_Spec::XG, "SynPiano"}},
    {midi_program_ex_id(00, 0x42, 0x75), Midi_Program_Ex{Midi_Spec::XG, "Rock Tom"}},
    {midi_program_ex_id(00, 0x43, 0x10), Midi_Program_Ex{Midi_Spec::XG, "DrawOrg3"}},
    {midi_program_ex_id(00, 0x43, 0x5a), Midi_Program_Ex{Midi_Spec::XG, "SquarPad"}},
    {midi_program_ex_id(00, 0x43, 0x5b), Midi_Program_Ex{Midi_Spec::XG, "CC Pad"}},
    {midi_program_ex_id(00, 0x43, 0x62), Midi_Program_Ex{Midi_Spec::XG, "XmasBell"}},
    {midi_program_ex_id(00, 0x43, 0x63), Midi_Program_Ex{Midi_Spec::XG, "Planet"}},
    {midi_program_ex_id(00, 0x43, 0x65), Midi_Program_Ex{Midi_Spec::XG, "Ritual"}},
    {midi_program_ex_id(00, 0x43, 0x66), Midi_Program_Ex{Midi_Spec::XG, "Creation"}},
    {midi_program_ex_id(00, 0x44, 0x62), Midi_Program_Ex{Midi_Spec::XG, "VibeBell"}},
    {midi_program_ex_id(00, 0x44, 0x65), Midi_Program_Ex{Midi_Spec::XG, "ToHeaven"}},
    {midi_program_ex_id(00, 0x44, 0x66), Midi_Program_Ex{Midi_Spec::XG, "Stardust"}},
    {midi_program_ex_id(00, 0x45, 0x62), Midi_Program_Ex{Midi_Spec::XG, "DigiBell"}},
    {midi_program_ex_id(00, 0x45, 0x66), Midi_Program_Ex{Midi_Spec::XG, "Reso Pan"}},
    {midi_program_ex_id(00, 0x46, 0x62), Midi_Program_Ex{Midi_Spec::XG, "AirBells"}},
    {midi_program_ex_id(00, 0x46, 0x65), Midi_Program_Ex{Midi_Spec::XG, "Night"}},
    {midi_program_ex_id(00, 0x47, 0x62), Midi_Program_Ex{Midi_Spec::XG, "BellHarp"}},
    {midi_program_ex_id(00, 0x47, 0x65), Midi_Program_Ex{Midi_Spec::XG, "Glisten"}},
    {midi_program_ex_id(00, 0x48, 0x62), Midi_Program_Ex{Midi_Spec::XG, "Gamelmba"}},
    {midi_program_ex_id(00, 0x60, 0xe), Midi_Program_Ex{Midi_Spec::XG, "Church Bell"}},
    {midi_program_ex_id(00, 0x60, 0xf), Midi_Program_Ex{Midi_Spec::XG, "Cimbalom"}},
    {midi_program_ex_id(00, 0x60, 0x18), Midi_Program_Ex{Midi_Spec::XG, "Ukelele"}},
    {midi_program_ex_id(00, 0x60, 0x19), Midi_Program_Ex{Midi_Spec::XG, "Mandolin"}},
    {midi_program_ex_id(00, 0x60, 0x23), Midi_Program_Ex{Midi_Spec::XG, "SynFretl"}},
    {midi_program_ex_id(00, 0x60, 0x26), Midi_Program_Ex{Midi_Spec::XG, "Hammer"}},
    {midi_program_ex_id(00, 0x60, 0x51), Midi_Program_Ex{Midi_Spec::XG, "Seq Ana"}},
    {midi_program_ex_id(00, 0x60, 0x64), Midi_Program_Ex{Midi_Spec::XG, "Smokey"}},
    {midi_program_ex_id(00, 0x60, 0x65), Midi_Program_Ex{Midi_Spec::XG, "BelChoir"}},
    {midi_program_ex_id(00, 0x60, 0x68), Midi_Program_Ex{Midi_Spec::XG, "Tambra"}},
    {midi_program_ex_id(00, 0x60, 0x69), Midi_Program_Ex{Midi_Spec::XG, "Rabab"}},
    {midi_program_ex_id(00, 0x60, 0x6b), Midi_Program_Ex{Midi_Spec::XG, "T.Koto"}},
    {midi_program_ex_id(00, 0x60, 0x6f), Midi_Program_Ex{Midi_Spec::XG, "Pungi"}},
    {midi_program_ex_id(00, 0x60, 0x70), Midi_Program_Ex{Midi_Spec::XG, "Bonang"}},
    {midi_program_ex_id(00, 0x60, 0x73), Midi_Program_Ex{Midi_Spec::XG, "Castanets"}},
    {midi_program_ex_id(00, 0x60, 0x74), Midi_Program_Ex{Midi_Spec::XG, "Gr.Cassa"}},
    {midi_program_ex_id(00, 0x61, 0xc), Midi_Program_Ex{Midi_Spec::XG, "Balafon2"}},
    {midi_program_ex_id(00, 0x61, 0xe), Midi_Program_Ex{Midi_Spec::XG, "Carillon"}},
    {midi_program_ex_id(00, 0x61, 0xf), Midi_Program_Ex{Midi_Spec::XG, "Santur"}},
    {midi_program_ex_id(00, 0x61, 0x23), Midi_Program_Ex{Midi_Spec::XG, "Smooth"}},
    {midi_program_ex_id(00, 0x61, 0x68), Midi_Program_Ex{Midi_Spec::XG, "Tamboura"}},
    {midi_program_ex_id(00, 0x61, 0x69), Midi_Program_Ex{Midi_Spec::XG, "Gopichnt"}},
    {midi_program_ex_id(00, 0x61, 0x6b), Midi_Program_Ex{Midi_Spec::XG, "Kanoon"}},
    {midi_program_ex_id(00, 0x61, 0x6f), Midi_Program_Ex{Midi_Spec::XG, "Hichriki"}},
    {midi_program_ex_id(00, 0x61, 0x70), Midi_Program_Ex{Midi_Spec::XG, "Gender"}},
    {midi_program_ex_id(00, 0x61, 0x72), Midi_Program_Ex{Midi_Spec::XG, "GlasPerc"}},
    {midi_program_ex_id(00, 0x62, 0xc), Midi_Program_Ex{Midi_Spec::XG, "Log Drum"}},
    {midi_program_ex_id(00, 0x62, 0x69), Midi_Program_Ex{Midi_Spec::XG, "Oud"}},
    {midi_program_ex_id(00, 0x62, 0x70), Midi_Program_Ex{Midi_Spec::XG, "Gamelan"}},
    {midi_program_ex_id(00, 0x62, 0x72), Midi_Program_Ex{Midi_Spec::XG, "ThaiBell"}},
    {midi_program_ex_id(00, 0x63, 0x70), Midi_Program_Ex{Midi_Spec::XG, "S.Gamlan"}},
    {midi_program_ex_id(00, 0x64, 0x70), Midi_Program_Ex{Midi_Spec::XG, "Rama Cym"}},
    {midi_program_ex_id(00, 0x65, 0x70), Midi_Program_Ex{Midi_Spec::XG, "AsianBel"}},
};

const Midi_Program_Ex *midi_program_ex_find(
    unsigned msb, unsigned lsb, unsigned pgm)
{
    auto it = midi_program_ex_map.find(
        midi_program_ex_id(msb, lsb, pgm));
    return (it != midi_program_ex_map.end()) ? &it->second : nullptr;
}
